Steps for fields Timebased features

1. Required Library Imports 
2. Loading the Dataset
3. Exploratory Data Analysis and Dirty Data Cleaning
4. Extracting Derived Variables

1. Required Library Imports

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from dateutil.relativedelta import relativedelta
from datetimerange import DateTimeRange
from dateutil import rrule, parser

2. Loading the Dataset

In [2]:
data=pd.read_csv('/home/ssg0283/Documents/RISK_MODELS/Code/pixar-scratchpad/data/cibil_timebased.csv')


#deal with empty values of dateClosed loans

3. Exploratory Data Analysis and Dirty Data Cleaning

In [3]:
display(data.dtypes)

_id                                                                                                                     object
intrimStatus.startTime                                                                                                  object
applicantComponentResponse.multiBureauJsonRespose.finishedList.responseJsonObject.accountList.dateOpenedOrDisbursed    float64
applicantComponentResponse.multiBureauJsonRespose.finishedList.responseJsonObject.accountList.dateClosed               float64
applicantComponentResponse.multiBureauJsonRespose.finishedList.responseJsonObject.accountList.accountType              float64
dtype: object

In [4]:
data.rename(columns={'_id': '_ID', 'intrimStatus.startTime': 'startTime','applicantComponentResponse.multiBureauJsonRespose.finishedList.responseJsonObject.accountList.dateOpenedOrDisbursed':'dateOpenedOrDisbursed','applicantComponentResponse.multiBureauJsonRespose.finishedList.responseJsonObject.accountList.dateClosed':'dateClosed','applicantComponentResponse.multiBureauJsonRespose.finishedList.responseJsonObject.accountList.accountType':'accountType'}, inplace=True)

display(data.dtypes)

_ID                       object
startTime                 object
dateOpenedOrDisbursed    float64
dateClosed               float64
accountType              float64
dtype: object

In [5]:
data.dropna(subset = ["dateOpenedOrDisbursed"], inplace=True)
data.head(10)

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,"{""$date"":""2020-07-28T07:09:40.569Z""}",30072016.0,14082018.0,13.0
17,28911006216,"{""$date"":""2020-07-28T07:09:36.776Z""}",23062020.0,NaN,7.0
18,28911006216,"{""$date"":""2020-07-28T07:09:36.776Z""}",17102019.0,29102019.0,7.0
19,28911006216,"{""$date"":""2020-07-28T07:09:36.776Z""}",15052019.0,17102019.0,7.0
33,33090002908,"{""$date"":""2020-07-28T07:09:15.183Z""}",28112014.0,11012016.0,0.0
34,33090002908,"{""$date"":""2020-07-28T07:09:15.183Z""}",20112013.0,28112014.0,0.0
36,47982003991,"{""$date"":""2020-07-28T07:09:14.487Z""}",13102019.0,NaN,6.0
37,47982003991,"{""$date"":""2020-07-28T07:09:14.487Z""}",23012019.0,28092019.0,6.0
39,28749004565,"{""$date"":""2020-07-28T07:09:14.358Z""}",3122019.0,NaN,5.0
40,28749004565,"{""$date"":""2020-07-28T07:09:14.358Z""}",27112019.0,NaN,52.0

In [6]:
data['dateOpenedOrDisbursed'].astype(int)
data.head(10)

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,"{""$date"":""2020-07-28T07:09:40.569Z""}",30072016.0,14082018.0,13.0
17,28911006216,"{""$date"":""2020-07-28T07:09:36.776Z""}",23062020.0,NaN,7.0
18,28911006216,"{""$date"":""2020-07-28T07:09:36.776Z""}",17102019.0,29102019.0,7.0
19,28911006216,"{""$date"":""2020-07-28T07:09:36.776Z""}",15052019.0,17102019.0,7.0
33,33090002908,"{""$date"":""2020-07-28T07:09:15.183Z""}",28112014.0,11012016.0,0.0
34,33090002908,"{""$date"":""2020-07-28T07:09:15.183Z""}",20112013.0,28112014.0,0.0
36,47982003991,"{""$date"":""2020-07-28T07:09:14.487Z""}",13102019.0,NaN,6.0
37,47982003991,"{""$date"":""2020-07-28T07:09:14.487Z""}",23012019.0,28092019.0,6.0
39,28749004565,"{""$date"":""2020-07-28T07:09:14.358Z""}",3122019.0,NaN,5.0
40,28749004565,"{""$date"":""2020-07-28T07:09:14.358Z""}",27112019.0,NaN,52.0

In [7]:
display(data.dtypes)

_ID                       object
startTime                 object
dateOpenedOrDisbursed    float64
dateClosed               float64
accountType              float64
dtype: object

In [8]:
data['startTime'] = data['startTime'].str.replace('Z','')
data['startTime'] = data['startTime'].str.replace('{','')
data['startTime'] = data['startTime'].str.replace('}','')
data['startTime'] = data['startTime'].str.replace('"','')
data['startTime'] = data['startTime'].str.replace('$','')
data['startTime'] = data['startTime'].str.replace('date:','')
data['startTime'] = data['startTime'].str.replace('T','')


data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,2020-07-2807:09:40.569,30072016.0,14082018.0,13.0
17,28911006216,2020-07-2807:09:36.776,23062020.0,NaN,7.0
18,28911006216,2020-07-2807:09:36.776,17102019.0,29102019.0,7.0
19,28911006216,2020-07-2807:09:36.776,15052019.0,17102019.0,7.0
33,33090002908,2020-07-2807:09:15.183,28112014.0,11012016.0,0.0

In [9]:
data['startTime'] =  pd.to_datetime(data['startTime'], format='%Y-%m-%d%H:%M:%S.%f')

In [10]:
data['dateOpenedOrDisbursed'] = data['dateOpenedOrDisbursed'].astype(int) 
data['dateClosed'] = data['dateClosed'].fillna(0)
data['dateClosed'] = data['dateClosed'].astype(int) 
data['accountType'] = data['accountType'].astype(int) 

data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,2020-07-28 07:09:40.569,30072016,14082018,13
17,28911006216,2020-07-28 07:09:36.776,23062020,0,7
18,28911006216,2020-07-28 07:09:36.776,17102019,29102019,7
19,28911006216,2020-07-28 07:09:36.776,15052019,17102019,7
33,33090002908,2020-07-28 07:09:15.183,28112014,11012016,0

In [11]:
data['dateOpenedOrDisbursed'] = data['dateOpenedOrDisbursed'].astype(str).apply(lambda x: x.zfill(8))
data['dateClosed'] = data['dateClosed'].astype(str).apply(lambda x: x.zfill(8))

data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,2020-07-28 07:09:40.569,30072016,14082018,13
17,28911006216,2020-07-28 07:09:36.776,23062020,00000000,7
18,28911006216,2020-07-28 07:09:36.776,17102019,29102019,7
19,28911006216,2020-07-28 07:09:36.776,15052019,17102019,7
33,33090002908,2020-07-28 07:09:15.183,28112014,11012016,0

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Replace the numerical values from accountType with the key coded values from Bureau Data Dictionary

In [12]:
bureau_accType_dict = {0: "OTH", 1: "AL", 2: "HL", 3: "HL", 4: "LAS", 5: "PL", 6: "CD",
                      7: "GL", 8: "PL", 9: "SEL", 10: "CC", 11: "HL", 12: "RL",
                      13: "AL", 14: "RL", 15: "LAS", 16: "CV", 17: "CV", 
                      31: "CC", 32: "AL", 33: "CV", 34: "CV", 35: "SCC", 36: "SCC",
                      37: "PL", 38: "RL", 39: "BL", 40: "MFBL", 41: "MFPL", 42: "MFHL",
                      43: "MFOT", 44: "HL", 50: "BL", 51: "BL", 52: "PLBL", 53: "PLBL",
                      54: "PLBL", 55: "RL", 56: "PLRLBL", 57: "PLRLBL", 58: "PLRLBL",
                      59: "BL", 61: "BL", 98: "SEC", 99: "UNSEC"}

In [13]:
data = data.replace({"accountType": bureau_accType_dict})
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,2020-07-28 07:09:40.569,30072016,14082018,AL
17,28911006216,2020-07-28 07:09:36.776,23062020,00000000,GL
18,28911006216,2020-07-28 07:09:36.776,17102019,29102019,GL
19,28911006216,2020-07-28 07:09:36.776,15052019,17102019,GL
33,33090002908,2020-07-28 07:09:15.183,28112014,11012016,OTH

In [14]:
data['dateOpenedOrDisbursed'] = data['dateOpenedOrDisbursed'].apply(lambda x: dt.datetime.strptime(x,'%d%m%Y'))
data['dateClosed'] =  pd.to_datetime(data['dateClosed'],errors='coerce', format = '%d%m%Y')
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,2020-07-28 07:09:40.569,2016-07-30,2018-08-14,AL
17,28911006216,2020-07-28 07:09:36.776,2020-06-23,NaT,GL
18,28911006216,2020-07-28 07:09:36.776,2019-10-17,2019-10-29,GL
19,28911006216,2020-07-28 07:09:36.776,2019-05-15,2019-10-17,GL
33,33090002908,2020-07-28 07:09:15.183,2014-11-28,2016-01-11,OTH

In [15]:
data['dateOpenedOrDisbursed'] = pd.to_datetime(data['dateOpenedOrDisbursed'],errors='coerce').dt.date
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType
9,67837000949,2020-07-28 07:09:40.569,2016-07-30,2018-08-14,AL
17,28911006216,2020-07-28 07:09:36.776,2020-06-23,NaT,GL
18,28911006216,2020-07-28 07:09:36.776,2019-10-17,2019-10-29,GL
19,28911006216,2020-07-28 07:09:36.776,2019-05-15,2019-10-17,GL
33,33090002908,2020-07-28 07:09:15.183,2014-11-28,2016-01-11,OTH

4. Extracting Derived Variables

In [16]:
data['startTime_Date'] = pd.to_datetime(data['startTime'],errors='coerce').dt.date

data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date
9,67837000949,2020-07-28 07:09:40.569,2016-07-30,2018-08-14,AL,2020-07-28
17,28911006216,2020-07-28 07:09:36.776,2020-06-23,NaT,GL,2020-07-28
18,28911006216,2020-07-28 07:09:36.776,2019-10-17,2019-10-29,GL,2020-07-28
19,28911006216,2020-07-28 07:09:36.776,2019-05-15,2019-10-17,GL,2020-07-28
33,33090002908,2020-07-28 07:09:15.183,2014-11-28,2016-01-11,OTH,2020-07-28

In [17]:
data['diff_startTime_dateOpened'] = ((data.startTime_Date - data.dateOpenedOrDisbursed)/np.timedelta64(1, 'M'))
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened
9,67837000949,2020-07-28 07:09:40.569,2016-07-30,2018-08-14,AL,2020-07-28,47.935276
17,28911006216,2020-07-28 07:09:36.776,2020-06-23,NaT,GL,2020-07-28,1.149921
18,28911006216,2020-07-28 07:09:36.776,2019-10-17,2019-10-29,GL,2020-07-28,9.363642
19,28911006216,2020-07-28 07:09:36.776,2019-05-15,2019-10-17,GL,2020-07-28,14.456149
33,33090002908,2020-07-28 07:09:15.183,2014-11-28,2016-01-11,OTH,2020-07-28,67.976755

In [18]:
data['diff_startTime_dateOpened'] = data['diff_startTime_dateOpened'].round().astype(int)
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened
9,67837000949,2020-07-28 07:09:40.569,2016-07-30,2018-08-14,AL,2020-07-28,48
17,28911006216,2020-07-28 07:09:36.776,2020-06-23,NaT,GL,2020-07-28,1
18,28911006216,2020-07-28 07:09:36.776,2019-10-17,2019-10-29,GL,2020-07-28,9
19,28911006216,2020-07-28 07:09:36.776,2019-05-15,2019-10-17,GL,2020-07-28,14
33,33090002908,2020-07-28 07:09:15.183,2014-11-28,2016-01-11,OTH,2020-07-28,68

In [19]:
data['dateClosed'] = pd.to_datetime(data['dateClosed'],errors='coerce').dt.date

In [20]:
data['dateOpenedOrDisbursed'].value_counts()

2019-10-31    16
2019-02-28    13
2017-02-18    12
2020-05-29    12
2020-03-16    12
              ..
2015-08-19     1
2015-02-06     1
2007-01-17     1
2017-05-27     1
2017-05-04     1
Name: dateOpenedOrDisbursed, Length: 1802, dtype: int64

In [21]:
data['diff_startTime_dateOpened'].value_counts()

9      151
8      147
7      117
11     116
10     112
      ...
158      1
170      1
178      1
121      1
247      1
Name: diff_startTime_dateOpened, Length: 195, dtype: int64

In [22]:
data['_ID'].value_counts()

25313011263        76
62382001759        61
3004CD0129013      56
33083002224        53
28086003293        52
                   ..
63037000631         1
77870000375         1
823701420000272     1
72966000271         1
28840001185         1
Name: _ID, Length: 593, dtype: int64

In [23]:
data.shape

(4125, 7)

In [24]:
data = data.groupby('_ID').agg(lambda x: x.tolist()).reset_index()
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened
0,25056002948,"[2020-07-28 06:56:21.616000, 2020-07-28 06:56:...","[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...","[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[55, 7, 22, 24, 26, 33, 33, 35, 37, 37, 40, 48..."
1,25057004362,"[2020-07-28 06:39:26.277000, 2020-07-28 06:39:...","[2019-12-27, 2018-12-11]","[NaT, NaT]","[PL, AL]","[2020-07-28, 2020-07-28]","[7, 20]"
2,25065002005,[2020-07-28 07:00:50.530000],[2013-11-28],[2014-04-30],[PLBL],[2020-07-28],[80]
3,25150006776,"[2020-07-28 06:24:14.232000, 2020-07-28 06:24:...","[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...","[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[0, 1, 1, 2, 2, 2, 3, 15, 19, 21, 25, 32, 38]"
4,25244001089,"[2020-07-28 06:34:27.226000, 2020-07-28 06:34:...","[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...","[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[74, 8, 12, 20, 25, 39, 42, 45, 49, 50, 73, 80..."

In [25]:
data.shape

(593, 7)

In [26]:
data.dtypes

_ID                          object
startTime                    object
dateOpenedOrDisbursed        object
dateClosed                   object
accountType                  object
startTime_Date               object
diff_startTime_dateOpened    object
dtype: object


Extracting Derived time variable (Set 1)
--
For an applicant, count of all loan accounts where difference between DateOpened and Login Date is <=[ (3, 6, 9) months, (1, 2, 3) years]

In [27]:
count_3M=0
count_6M=0
count_9M=0
count_1Y=0
count_2Y=0
count_3Y=0
data['opened_last3M_CNT']=0
data['opened_last6M_CNT']=0
data['opened_last9M_CNT']=0
data['opened_last1Y_CNT']=0
data['opened_last2Y_CNT']=0
data['opened_last3Y_CNT']=0

for i in range(data.shape[0]):
    count_3M=0
    count_6M=0
    count_9M=0
    count_1Y=0
    count_2Y=0
    count_3Y=0
    for j in data['diff_startTime_dateOpened'][i]:
        if j<=3:
            count_3M = count_3M+1
        data['opened_last3M_CNT'][i] = count_3M
        
        if j<=6:
            count_6M = count_6M+1
        data['opened_last6M_CNT'][i] = count_6M
        
        if j<=9:
            count_9M = count_9M+1
        data['opened_last9M_CNT'][i] = count_9M
        
        if j<=12:
            count_1Y = count_1Y+1
        data['opened_last1Y_CNT'][i] = count_1Y
        
        if j<=24:
            count_2Y = count_2Y+1
        data['opened_last2Y_CNT'][i] = count_2Y
        
        if j<=36:
            count_3Y = count_3Y+1
        data['opened_last3Y_CNT'][i] = count_3Y
        
data.head()

/home/ssg0283/environments/NewENv/yes/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/ssg0283/environments/NewENv/yes/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/ssg0283/environments/NewENv/yes/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/ssg0283/environments/NewENv/yes/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/ssg0283/environments/NewENv/yes/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/ssg0283/environments/NewENv/yes/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened,opened_last3M_CNT,opened_last6M_CNT,opened_last9M_CNT,opened_last1Y_CNT,opened_last2Y_CNT,opened_last3Y_CNT
0,25056002948,"[2020-07-28 06:56:21.616000, 2020-07-28 06:56:...","[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...","[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[55, 7, 22, 24, 26, 33, 33, 35, 37, 37, 40, 48...",0,0,1,1,3,7
1,25057004362,"[2020-07-28 06:39:26.277000, 2020-07-28 06:39:...","[2019-12-27, 2018-12-11]","[NaT, NaT]","[PL, AL]","[2020-07-28, 2020-07-28]","[7, 20]",0,0,1,1,2,2
2,25065002005,[2020-07-28 07:00:50.530000],[2013-11-28],[2014-04-30],[PLBL],[2020-07-28],[80],0,0,0,0,0,0
3,25150006776,"[2020-07-28 06:24:14.232000, 2020-07-28 06:24:...","[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...","[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[0, 1, 1, 2, 2, 2, 3, 15, 19, 21, 25, 32, 38]",7,7,7,7,10,12
4,25244001089,"[2020-07-28 06:34:27.226000, 2020-07-28 06:34:...","[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...","[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[74, 8, 12, 20, 25, 39, 42, 45, 49, 50, 73, 80...",0,0,1,2,3,6


Extracting Derived time variable (Set 2)
--
For an applicant, generalized count list of all loan accounts where difference between DateOpened and Login Date is <=[ (3, 6, 9) months, (1, 2, 3) years] per product

In [28]:
date_before_3M = dt.date
date_before_6M = dt.date
date_before_9M = dt.date
date_before_1Y = dt.date
date_before_2Y = dt.date
date_before_3Y = dt.date


three_mon_rel = relativedelta(months=-3)
six_mon_rel = relativedelta(months=-6)
nine_mon_rel = relativedelta(months=-9)
one_year_rel = relativedelta(months=-12)
two_year_rel = relativedelta(months=-24)
three_year_rel = relativedelta(months=-36)


opened_last3M_CNT_P_list= []
opened_last6M_CNT_P_list= []
opened_last9M_CNT_P_list= []
opened_last1Y_CNT_P_list= []
opened_last2Y_CNT_P_list= []
opened_last3Y_CNT_P_list= []



data['opened_last3M_CNT_P'] = 0
data['opened_last6M_CNT_P'] = 0
data['opened_last9M_CNT_P'] = 0
data['opened_last1Y_CNT_P'] = 0
data['opened_last2Y_CNT_P'] = 0
data['opened_last3Y_CNT_P'] = 0


data['opened_last3M_CNT_P'] = data['opened_last3M_CNT_P'].astype(object)
data['opened_last6M_CNT_P'] = data['opened_last6M_CNT_P'].astype(object)
data['opened_last9M_CNT_P'] = data['opened_last9M_CNT_P'].astype(object)
data['opened_last1Y_CNT_P'] = data['opened_last1Y_CNT_P'].astype(object)
data['opened_last2Y_CNT_P'] = data['opened_last2Y_CNT_P'].astype(object)
data['opened_last3Y_CNT_P'] = data['opened_last3Y_CNT_P'].astype(object)


#date_before_3M = (data['dateOpenedOrDisbursed'][1][1]) + three_mon_rel
#date_before_3M = dt.date

#print(date_before_3M)

In [29]:
def search_dt_list(dateOpenedDisbursed_start,date_before_period, dateOpenedDisbursedlist):
    count=0
    for p in dateOpenedDisbursedlist:
        if dateOpenedDisbursed_start!=p and dateOpenedDisbursed_start > p >= date_before_period:
            count = count + 1
    return count

In [30]:
for i in range(data.shape[0]):
    opened_last3M_CNT_P_list = []
    opened_last6M_CNT_P_list = []
    opened_last9M_CNT_P_list = []
    opened_last1Y_CNT_P_list = []
    opened_last2Y_CNT_P_list = []
    opened_last3Y_CNT_P_list = []
    
    for j in data['dateOpenedOrDisbursed'][i]:
        date_before_3M = j + three_mon_rel
        date_before_6M = j + six_mon_rel
        date_before_9M = j + nine_mon_rel
        date_before_1Y = j + one_year_rel
        date_before_2Y = j + two_year_rel
        date_before_3Y = j + three_year_rel
        
        
        
        opened_last3M_CNT_P_list.append(search_dt_list(j,date_before_3M, data['dateOpenedOrDisbursed'][i]))
        opened_last6M_CNT_P_list.append(search_dt_list(j,date_before_6M, data['dateOpenedOrDisbursed'][i]))
        opened_last9M_CNT_P_list.append(search_dt_list(j,date_before_9M, data['dateOpenedOrDisbursed'][i]))
        opened_last1Y_CNT_P_list.append(search_dt_list(j,date_before_1Y, data['dateOpenedOrDisbursed'][i]))
        opened_last2Y_CNT_P_list.append(search_dt_list(j,date_before_2Y, data['dateOpenedOrDisbursed'][i]))
        opened_last3Y_CNT_P_list.append(search_dt_list(j,date_before_3Y, data['dateOpenedOrDisbursed'][i]))
        
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_P')] = opened_last3M_CNT_P_list
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_P')] = opened_last6M_CNT_P_list
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_P')] = opened_last9M_CNT_P_list
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_P')] = opened_last1Y_CNT_P_list
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_P')] = opened_last2Y_CNT_P_list
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_P')] = opened_last3Y_CNT_P_list
    

data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened,opened_last3M_CNT,opened_last6M_CNT,opened_last9M_CNT,opened_last1Y_CNT,opened_last2Y_CNT,opened_last3Y_CNT,opened_last3M_CNT_P,opened_last6M_CNT_P,opened_last9M_CNT_P,opened_last1Y_CNT_P,opened_last2Y_CNT_P,opened_last3Y_CNT_P
0,25056002948,"[2020-07-28 06:56:21.616000, 2020-07-28 06:56:...","[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...","[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[55, 7, 22, 24, 26, 33, 33, 35, 37, 37, 40, 48...",0,0,1,1,3,7,"[0, 0, 1, 1, 0, 2, 1, 2, 1, 0, 0, 3, 3, 2, 1, ...","[0, 0, 2, 1, 0, 4, 3, 3, 2, 1, 0, 4, 4, 3, 3, ...","[0, 0, 2, 2, 2, 5, 4, 3, 2, 1, 4, 5, 5, 4, 3, ...","[0, 0, 4, 4, 5, 5, 4, 3, 5, 4, 5, 5, 5, 4, 3, ...","[0, 3, 8, 9, 11, 12, 11, 10, 9, 8, 7, 5, 5, 4,...","[1, 9, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 6, ..."
1,25057004362,"[2020-07-28 06:39:26.277000, 2020-07-28 06:39:...","[2019-12-27, 2018-12-11]","[NaT, NaT]","[PL, AL]","[2020-07-28, 2020-07-28]","[7, 20]",0,0,1,1,2,2,"[0, 0]","[0, 0]","[0, 0]","[0, 0]","[1, 0]","[1, 0]"
2,25065002005,[2020-07-28 07:00:50.530000],[2013-11-28],[2014-04-30],[PLBL],[2020-07-28],[80],0,0,0,0,0,0,[0],[0],[0],[0],[0],[0]
3,25150006776,"[2020-07-28 06:24:14.232000, 2020-07-28 06:24:...","[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...","[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[0, 1, 1, 2, 2, 2, 3, 15, 19, 21, 25, 32, 38]",7,7,7,7,10,12,"[6, 5, 4, 2, 2, 1, 0, 0, 1, 0, 0, 0, 0]","[6, 5, 4, 2, 2, 1, 0, 2, 1, 1, 0, 0, 0]","[6, 5, 4, 2, 2, 1, 0, 2, 2, 1, 1, 1, 0]","[6, 5, 4, 2, 2, 1, 1, 3, 2, 2, 1, 1, 0]","[9, 8, 8, 6, 6, 5, 4, 5, 4, 3, 2, 1, 0]","[11, 10, 9, 7, 7, 6, 6, 5, 4, 3, 2, 1, 0]"
4,25244001089,"[2020-07-28 06:34:27.226000, 2020-07-28 06:34:...","[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...","[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[74, 8, 12, 20, 25, 39, 42, 45, 49, 50, 73, 80...",0,0,1,2,3,6,"[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, ...","[0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 1, 0, 2, ...","[1, 1, 1, 3, 2, 2, 3, 2, 1, 0, 2, 2, 1, 1, 2, ...","[2, 1, 1, 3, 2, 4, 3, 2, 1, 0, 3, 2, 2, 1, 2, ...","[4, 5, 4, 5, 6, 4, 3, 2, 2, 2, 5, 6, 5, 4, 2, ...","[7, 7, 7, 8, 7, 6, 5, 5, 5, 5, 8, 6, 5, 4, 2, ..."

Extracting Derived time variable (Set 3)
--
For an applicant, count of all loan accounts where difference between DateOpened and Login Date is <=[ (3, 6, 9) months, (1, 2, 3) years] per product group

In [31]:
data['opened_last3M_CNT_PL'] = 0
data['opened_last6M_CNT_PL'] = 0
data['opened_last9M_CNT_PL'] = 0
data['opened_last1Y_CNT_PL'] = 0
data['opened_last2Y_CNT_PL'] = 0
data['opened_last3Y_CNT_PL'] = 0



data['opened_last3M_CNT_HL'] = 0
data['opened_last6M_CNT_HL'] = 0
data['opened_last9M_CNT_HL'] = 0
data['opened_last1Y_CNT_HL'] = 0
data['opened_last2Y_CNT_HL'] = 0
data['opened_last3Y_CNT_HL'] = 0


data['opened_last3M_CNT_GL'] = 0
data['opened_last6M_CNT_GL'] = 0
data['opened_last9M_CNT_GL'] = 0
data['opened_last1Y_CNT_GL'] = 0
data['opened_last2Y_CNT_GL'] = 0
data['opened_last3Y_CNT_GL'] = 0



data['opened_last3M_CNT_AL'] = 0
data['opened_last6M_CNT_AL'] = 0
data['opened_last9M_CNT_AL'] = 0
data['opened_last1Y_CNT_AL'] = 0
data['opened_last2Y_CNT_AL'] = 0
data['opened_last3Y_CNT_AL'] = 0



data['opened_last3M_CNT_SEL'] = 0
data['opened_last6M_CNT_SEL'] = 0
data['opened_last9M_CNT_SEL'] = 0
data['opened_last1Y_CNT_SEL'] = 0
data['opened_last2Y_CNT_SEL'] = 0
data['opened_last3Y_CNT_SEL'] = 0



data['opened_last3M_CNT_LAS'] = 0
data['opened_last6M_CNT_LAS'] = 0
data['opened_last9M_CNT_LAS'] = 0
data['opened_last1Y_CNT_LAS'] = 0
data['opened_last2Y_CNT_LAS'] = 0
data['opened_last3Y_CNT_LAS'] = 0



data['opened_last3M_CNT_CD'] = 0
data['opened_last6M_CNT_CD'] = 0
data['opened_last9M_CNT_CD'] = 0
data['opened_last1Y_CNT_CD'] = 0
data['opened_last2Y_CNT_CD'] = 0
data['opened_last3Y_CNT_CD'] = 0



data['opened_last3M_CNT_CC'] = 0
data['opened_last6M_CNT_CC'] = 0
data['opened_last9M_CNT_CC'] = 0
data['opened_last1Y_CNT_CC'] = 0
data['opened_last2Y_CNT_CC'] = 0
data['opened_last3Y_CNT_CC'] = 0


data['opened_last3M_CNT_RL'] = 0
data['opened_last6M_CNT_RL'] = 0
data['opened_last9M_CNT_RL'] = 0
data['opened_last1Y_CNT_RL'] = 0
data['opened_last2Y_CNT_RL'] = 0
data['opened_last3Y_CNT_RL'] = 0



data['opened_last3M_CNT_CV'] = 0
data['opened_last6M_CNT_CV'] = 0
data['opened_last9M_CNT_CV'] = 0
data['opened_last1Y_CNT_CV'] = 0
data['opened_last2Y_CNT_CV'] = 0
data['opened_last3Y_CNT_CV'] = 0


data['opened_last3M_CNT_SCC'] = 0
data['opened_last6M_CNT_SCC'] = 0
data['opened_last9M_CNT_SCC'] = 0
data['opened_last1Y_CNT_SCC'] = 0
data['opened_last2Y_CNT_SCC'] = 0
data['opened_last3Y_CNT_SCC'] = 0



data['opened_last3M_CNT_BL'] = 0
data['opened_last6M_CNT_BL'] = 0
data['opened_last9M_CNT_BL'] = 0
data['opened_last1Y_CNT_BL'] = 0
data['opened_last2Y_CNT_BL'] = 0
data['opened_last3Y_CNT_BL'] = 0


data['opened_last3M_CNT_MFBL'] = 0
data['opened_last6M_CNT_MFBL'] = 0
data['opened_last9M_CNT_MFBL'] = 0
data['opened_last1Y_CNT_MFBL'] = 0
data['opened_last2Y_CNT_MFBL'] = 0
data['opened_last3Y_CNT_MFBL'] = 0

data['opened_last3M_CNT_MFPL'] = 0
data['opened_last6M_CNT_MFPL'] = 0
data['opened_last9M_CNT_MFPL'] = 0
data['opened_last1Y_CNT_MFPL'] = 0
data['opened_last2Y_CNT_MFPL'] = 0
data['opened_last3Y_CNT_MFPL'] = 0


data['opened_last3M_CNT_MFHL'] = 0
data['opened_last6M_CNT_MFHL'] = 0
data['opened_last9M_CNT_MFHL'] = 0
data['opened_last1Y_CNT_MFHL'] = 0
data['opened_last2Y_CNT_MFHL'] = 0
data['opened_last3Y_CNT_MFHL'] = 0


data['opened_last3M_CNT_MFOT'] = 0
data['opened_last6M_CNT_MFOT'] = 0
data['opened_last9M_CNT_MFOT'] = 0
data['opened_last1Y_CNT_MFOT'] = 0
data['opened_last2Y_CNT_MFOT'] = 0
data['opened_last3Y_CNT_MFOT'] = 0



data['opened_last3M_CNT_OTH'] = 0
data['opened_last6M_CNT_OTH'] = 0
data['opened_last9M_CNT_OTH'] = 0
data['opened_last1Y_CNT_OTH'] = 0
data['opened_last2Y_CNT_OTH'] = 0
data['opened_last3Y_CNT_OTH'] = 0



data['opened_last3M_CNT_PLBL'] = 0
data['opened_last6M_CNT_PLBL'] = 0
data['opened_last9M_CNT_PLBL'] = 0
data['opened_last1Y_CNT_PLBL'] = 0
data['opened_last2Y_CNT_PLBL'] = 0
data['opened_last3Y_CNT_PLBL'] = 0



data['opened_last3M_CNT_PLRLBL'] = 0 
data['opened_last6M_CNT_PLRLBL'] = 0
data['opened_last9M_CNT_PLRLBL'] = 0
data['opened_last1Y_CNT_PLRLBL'] = 0
data['opened_last2Y_CNT_PLRLBL'] = 0
data['opened_last3Y_CNT_PLRLBL'] = 0



data['opened_last3M_CNT_SEC'] = 0
data['opened_last6M_CNT_SEC'] = 0
data['opened_last9M_CNT_SEC'] = 0
data['opened_last1Y_CNT_SEC'] = 0
data['opened_last2Y_CNT_SEC'] = 0
data['opened_last3Y_CNT_SEC'] = 0



data['opened_last3M_CNT_UNSEC'] = 0 
data['opened_last6M_CNT_UNSEC'] = 0
data['opened_last9M_CNT_UNSEC'] = 0
data['opened_last1Y_CNT_UNSEC'] = 0
data['opened_last2Y_CNT_UNSEC'] = 0
data['opened_last3Y_CNT_UNSEC'] = 0

In [32]:
data['opened_last3M_CNT_PL'] = data['opened_last3M_CNT_PL'].astype(object)
data['opened_last6M_CNT_PL'] = data['opened_last6M_CNT_PL'].astype(object)
data['opened_last9M_CNT_PL'] = data['opened_last9M_CNT_PL'].astype(object)
data['opened_last1Y_CNT_PL'] = data['opened_last1Y_CNT_PL'].astype(object)
data['opened_last2Y_CNT_PL'] = data['opened_last2Y_CNT_PL'].astype(object)
data['opened_last3Y_CNT_PL'] = data['opened_last3Y_CNT_PL'].astype(object)



data['opened_last3M_CNT_HL'] = data['opened_last3M_CNT_HL'].astype(object)
data['opened_last6M_CNT_HL'] = data['opened_last6M_CNT_HL'].astype(object)
data['opened_last9M_CNT_HL'] = data['opened_last9M_CNT_HL'].astype(object)
data['opened_last1Y_CNT_HL'] = data['opened_last1Y_CNT_HL'].astype(object)
data['opened_last2Y_CNT_HL'] = data['opened_last2Y_CNT_HL'].astype(object)
data['opened_last3Y_CNT_HL'] = data['opened_last3Y_CNT_HL'].astype(object)


data['opened_last3M_CNT_GL'] = data['opened_last3M_CNT_GL'].astype(object)
data['opened_last6M_CNT_GL'] = data['opened_last6M_CNT_GL'].astype(object)
data['opened_last9M_CNT_GL'] = data['opened_last9M_CNT_GL'].astype(object)
data['opened_last1Y_CNT_GL'] = data['opened_last1Y_CNT_GL'].astype(object)
data['opened_last2Y_CNT_GL'] = data['opened_last2Y_CNT_GL'].astype(object)
data['opened_last3Y_CNT_GL'] = data['opened_last3Y_CNT_GL'].astype(object)



data['opened_last3M_CNT_AL'] = data['opened_last3M_CNT_AL'].astype(object)
data['opened_last6M_CNT_AL'] = data['opened_last6M_CNT_AL'].astype(object)
data['opened_last9M_CNT_AL'] = data['opened_last9M_CNT_AL'].astype(object)
data['opened_last1Y_CNT_AL'] = data['opened_last1Y_CNT_AL'].astype(object)
data['opened_last2Y_CNT_AL'] = data['opened_last2Y_CNT_AL'].astype(object)
data['opened_last3Y_CNT_AL'] = data['opened_last3Y_CNT_AL'].astype(object)


data['opened_last3M_CNT_SEL'] = data['opened_last3M_CNT_SEL'].astype(object)
data['opened_last6M_CNT_SEL'] = data['opened_last6M_CNT_SEL'].astype(object)
data['opened_last9M_CNT_SEL'] = data['opened_last9M_CNT_SEL'].astype(object)
data['opened_last1Y_CNT_SEL'] = data['opened_last1Y_CNT_SEL'].astype(object)
data['opened_last2Y_CNT_SEL'] = data['opened_last2Y_CNT_SEL'].astype(object)
data['opened_last3Y_CNT_SEL'] = data['opened_last3Y_CNT_SEL'].astype(object)



data['opened_last3M_CNT_LAS'] = data['opened_last3M_CNT_LAS'].astype(object)
data['opened_last6M_CNT_LAS'] = data['opened_last6M_CNT_LAS'].astype(object)
data['opened_last9M_CNT_LAS'] = data['opened_last9M_CNT_LAS'].astype(object)
data['opened_last1Y_CNT_LAS'] = data['opened_last1Y_CNT_LAS'].astype(object)
data['opened_last2Y_CNT_LAS'] = data['opened_last2Y_CNT_LAS'].astype(object)
data['opened_last3Y_CNT_LAS'] = data['opened_last3Y_CNT_LAS'].astype(object)



data['opened_last3M_CNT_CD'] = data['opened_last3M_CNT_CD'].astype(object)
data['opened_last6M_CNT_CD'] = data['opened_last6M_CNT_CD'].astype(object)
data['opened_last9M_CNT_CD'] = data['opened_last9M_CNT_CD'].astype(object)
data['opened_last1Y_CNT_CD'] = data['opened_last1Y_CNT_CD'].astype(object)
data['opened_last2Y_CNT_CD'] = data['opened_last2Y_CNT_CD'].astype(object)
data['opened_last3Y_CNT_CD'] = data['opened_last3Y_CNT_CD'].astype(object)



data['opened_last3M_CNT_CC'] = data['opened_last3M_CNT_CC'].astype(object)
data['opened_last6M_CNT_CC'] = data['opened_last6M_CNT_CC'].astype(object)
data['opened_last9M_CNT_CC'] = data['opened_last9M_CNT_CC'].astype(object)
data['opened_last1Y_CNT_CC'] = data['opened_last1Y_CNT_CC'].astype(object)
data['opened_last2Y_CNT_CC'] = data['opened_last2Y_CNT_CC'].astype(object)
data['opened_last3Y_CNT_CC'] = data['opened_last3Y_CNT_CC'].astype(object)


data['opened_last3M_CNT_RL'] = data['opened_last3M_CNT_RL'].astype(object)
data['opened_last6M_CNT_RL'] = data['opened_last6M_CNT_RL'].astype(object)
data['opened_last9M_CNT_RL'] = data['opened_last9M_CNT_RL'].astype(object)
data['opened_last1Y_CNT_RL'] = data['opened_last1Y_CNT_RL'].astype(object)
data['opened_last2Y_CNT_RL'] = data['opened_last2Y_CNT_RL'].astype(object)
data['opened_last3Y_CNT_RL'] = data['opened_last3Y_CNT_RL'].astype(object)



data['opened_last3M_CNT_CV'] = data['opened_last3M_CNT_CV'].astype(object)
data['opened_last6M_CNT_CV'] = data['opened_last6M_CNT_CV'].astype(object)
data['opened_last9M_CNT_CV'] = data['opened_last9M_CNT_CV'].astype(object)
data['opened_last1Y_CNT_CV'] = data['opened_last1Y_CNT_CV'].astype(object)
data['opened_last2Y_CNT_CV'] = data['opened_last2Y_CNT_CV'].astype(object)
data['opened_last3Y_CNT_CV'] = data['opened_last3Y_CNT_CV'].astype(object)


data['opened_last3M_CNT_SCC'] = data['opened_last3M_CNT_SCC'].astype(object)
data['opened_last6M_CNT_SCC'] = data['opened_last6M_CNT_SCC'].astype(object)
data['opened_last9M_CNT_SCC'] = data['opened_last9M_CNT_SCC'].astype(object)
data['opened_last1Y_CNT_SCC'] = data['opened_last1Y_CNT_SCC'].astype(object)
data['opened_last2Y_CNT_SCC'] = data['opened_last2Y_CNT_SCC'].astype(object)
data['opened_last3Y_CNT_SCC'] = data['opened_last3Y_CNT_SCC'].astype(object)



data['opened_last3M_CNT_BL'] = data['opened_last3M_CNT_BL'].astype(object)
data['opened_last6M_CNT_BL'] = data['opened_last6M_CNT_BL'].astype(object)
data['opened_last9M_CNT_BL'] = data['opened_last9M_CNT_BL'].astype(object)
data['opened_last1Y_CNT_BL'] = data['opened_last1Y_CNT_BL'].astype(object)
data['opened_last2Y_CNT_BL'] = data['opened_last2Y_CNT_BL'].astype(object)
data['opened_last3Y_CNT_BL'] = data['opened_last3Y_CNT_BL'].astype(object)


data['opened_last3M_CNT_MFBL'] = data['opened_last3M_CNT_MFBL'].astype(object)
data['opened_last6M_CNT_MFBL'] = data['opened_last6M_CNT_MFBL'].astype(object)
data['opened_last9M_CNT_MFBL'] = data['opened_last9M_CNT_MFBL'].astype(object)
data['opened_last1Y_CNT_MFBL'] = data['opened_last1Y_CNT_MFBL'].astype(object)
data['opened_last2Y_CNT_MFBL'] = data['opened_last2Y_CNT_MFBL'].astype(object)
data['opened_last3Y_CNT_MFBL'] = data['opened_last3Y_CNT_MFBL'].astype(object)

data['opened_last3M_CNT_MFPL'] = data['opened_last3M_CNT_MFPL'].astype(object)
data['opened_last6M_CNT_MFPL'] = data['opened_last6M_CNT_MFPL'].astype(object)
data['opened_last9M_CNT_MFPL'] = data['opened_last9M_CNT_MFPL'].astype(object)
data['opened_last1Y_CNT_MFPL'] = data['opened_last1Y_CNT_MFPL'].astype(object)
data['opened_last2Y_CNT_MFPL'] = data['opened_last2Y_CNT_MFPL'].astype(object)
data['opened_last3Y_CNT_MFPL'] = data['opened_last3Y_CNT_MFPL'].astype(object)





data['opened_last3M_CNT_MFHL'] = data['opened_last3M_CNT_MFHL'].astype(object)
data['opened_last6M_CNT_MFHL'] = data['opened_last6M_CNT_MFHL'].astype(object)
data['opened_last9M_CNT_MFHL'] = data['opened_last9M_CNT_MFHL'].astype(object)
data['opened_last1Y_CNT_MFHL'] = data['opened_last1Y_CNT_MFHL'].astype(object)
data['opened_last2Y_CNT_MFHL'] = data['opened_last2Y_CNT_MFHL'].astype(object)
data['opened_last3Y_CNT_MFHL'] = data['opened_last3Y_CNT_MFHL'].astype(object)


data['opened_last3M_CNT_MFOT'] = data['opened_last3M_CNT_MFOT'].astype(object)
data['opened_last6M_CNT_MFOT'] = data['opened_last6M_CNT_MFOT'].astype(object)
data['opened_last9M_CNT_MFOT'] = data['opened_last9M_CNT_MFOT'].astype(object)
data['opened_last1Y_CNT_MFOT'] = data['opened_last1Y_CNT_MFOT'].astype(object)
data['opened_last2Y_CNT_MFOT'] = data['opened_last2Y_CNT_MFOT'].astype(object)
data['opened_last3Y_CNT_MFOT'] = data['opened_last3Y_CNT_MFOT'].astype(object)



data['opened_last3M_CNT_OTH'] = data['opened_last3M_CNT_OTH'].astype(object)
data['opened_last6M_CNT_OTH'] = data['opened_last6M_CNT_OTH'].astype(object)
data['opened_last9M_CNT_OTH'] = data['opened_last9M_CNT_OTH'].astype(object)
data['opened_last1Y_CNT_OTH'] = data['opened_last1Y_CNT_OTH'].astype(object)
data['opened_last2Y_CNT_OTH'] = data['opened_last2Y_CNT_OTH'].astype(object)
data['opened_last3Y_CNT_OTH'] = data['opened_last3Y_CNT_OTH'].astype(object)



data['opened_last3M_CNT_PLBL'] = data['opened_last3M_CNT_PLBL'].astype(object)
data['opened_last6M_CNT_PLBL'] = data['opened_last6M_CNT_PLBL'].astype(object)
data['opened_last9M_CNT_PLBL'] = data['opened_last9M_CNT_PLBL'].astype(object)
data['opened_last1Y_CNT_PLBL'] = data['opened_last1Y_CNT_PLBL'].astype(object)
data['opened_last2Y_CNT_PLBL'] = data['opened_last2Y_CNT_PLBL'].astype(object)
data['opened_last3Y_CNT_PLBL'] = data['opened_last3Y_CNT_PLBL'].astype(object)



data['opened_last3M_CNT_PLRLBL'] = data['opened_last3M_CNT_PLRLBL'].astype(object)
data['opened_last6M_CNT_PLRLBL'] = data['opened_last6M_CNT_PLRLBL'].astype(object)
data['opened_last9M_CNT_PLRLBL'] = data['opened_last9M_CNT_PLRLBL'].astype(object)
data['opened_last1Y_CNT_PLRLBL'] = data['opened_last1Y_CNT_PLRLBL'].astype(object)
data['opened_last2Y_CNT_PLRLBL'] = data['opened_last2Y_CNT_PLRLBL'].astype(object)
data['opened_last3Y_CNT_PLRLBL'] = data['opened_last3Y_CNT_PLRLBL'].astype(object)



data['opened_last3M_CNT_SEC'] = data['opened_last3M_CNT_SEC'].astype(object)
data['opened_last6M_CNT_SEC'] = data['opened_last6M_CNT_SEC'].astype(object)
data['opened_last9M_CNT_SEC'] = data['opened_last9M_CNT_SEC'].astype(object)
data['opened_last1Y_CNT_SEC'] = data['opened_last1Y_CNT_SEC'].astype(object)
data['opened_last2Y_CNT_SEC'] = data['opened_last2Y_CNT_SEC'].astype(object)
data['opened_last3Y_CNT_SEC'] = data['opened_last3Y_CNT_SEC'].astype(object)



data['opened_last3M_CNT_UNSEC'] = data['opened_last3M_CNT_UNSEC'].astype(object)
data['opened_last6M_CNT_UNSEC'] = data['opened_last6M_CNT_UNSEC'].astype(object)
data['opened_last9M_CNT_UNSEC'] = data['opened_last9M_CNT_UNSEC'].astype(object)
data['opened_last1Y_CNT_UNSEC'] = data['opened_last1Y_CNT_UNSEC'].astype(object)
data['opened_last2Y_CNT_UNSEC'] = data['opened_last2Y_CNT_UNSEC'].astype(object)
data['opened_last3Y_CNT_UNSEC'] = data['opened_last3Y_CNT_UNSEC'].astype(object)

In [33]:
data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened,opened_last3M_CNT,opened_last6M_CNT,opened_last9M_CNT,...,opened_last9M_CNT_SEC,opened_last1Y_CNT_SEC,opened_last2Y_CNT_SEC,opened_last3Y_CNT_SEC,opened_last3M_CNT_UNSEC,opened_last6M_CNT_UNSEC,opened_last9M_CNT_UNSEC,opened_last1Y_CNT_UNSEC,opened_last2Y_CNT_UNSEC,opened_last3Y_CNT_UNSEC
0,25056002948,"[2020-07-28 06:56:21.616000, 2020-07-28 06:56:...","[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...","[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[55, 7, 22, 24, 26, 33, 33, 35, 37, 37, 40, 48...",0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,25057004362,"[2020-07-28 06:39:26.277000, 2020-07-28 06:39:...","[2019-12-27, 2018-12-11]","[NaT, NaT]","[PL, AL]","[2020-07-28, 2020-07-28]","[7, 20]",0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,25065002005,[2020-07-28 07:00:50.530000],[2013-11-28],[2014-04-30],[PLBL],[2020-07-28],[80],0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,25150006776,"[2020-07-28 06:24:14.232000, 2020-07-28 06:24:...","[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...","[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[0, 1, 1, 2, 2, 2, 3, 15, 19, 21, 25, 32, 38]",7,7,7,...,0,0,0,0,0,0,0,0,0,0
4,25244001089,"[2020-07-28 06:34:27.226000, 2020-07-28 06:34:...","[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...","[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[74, 8, 12, 20, 25, 39, 42, 45, 49, 50, 73, 80...",0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [34]:
def search_dt_cnt(i, j, accountType_var, startTime_Date, date_before_period, dateOpened_dateClosed_list, accountType_list):
    count=0
    #print(j)
    for p in range(len(accountType_list)):
        if accountType_list[p]==accountType_var and startTime_Date >= dateOpened_dateClosed_list[p] >= date_before_period and dateOpened_dateClosed_list[p]!= "NaT":
            count = count + 1
    return count

In [35]:
for i in range(data.shape[0]):
    opened_last3M_CNT_HL_val = 0
    opened_last6M_CNT_HL_val = 0
    opened_last9M_CNT_HL_val = 0
    opened_last1Y_CNT_HL_val = 0
    opened_last2Y_CNT_HL_val = 0
    opened_last3Y_CNT_HL_val = 0
    
    opened_last3M_CNT_GL_val = 0
    opened_last6M_CNT_GL_val = 0
    opened_last9M_CNT_GL_val = 0
    opened_last1Y_CNT_GL_val = 0
    opened_last2Y_CNT_GL_val = 0
    opened_last3Y_CNT_GL_val = 0
    
    opened_last3M_CNT_AL_val = 0
    opened_last6M_CNT_AL_val = 0
    opened_last9M_CNT_AL_val = 0
    opened_last1Y_CNT_AL_val = 0
    opened_last2Y_CNT_AL_val = 0
    opened_last3Y_CNT_AL_val = 0
    
    opened_last3M_CNT_LAS_val = 0
    opened_last6M_CNT_LAS_val = 0
    opened_last9M_CNT_LAS_val = 0
    opened_last1Y_CNT_LAS_val = 0
    opened_last2Y_CNT_LAS_val = 0
    opened_last3Y_CNT_LAS_val = 0
    
    opened_last3M_CNT_PL_val = 0
    opened_last6M_CNT_PL_val = 0
    opened_last9M_CNT_PL_val = 0
    opened_last1Y_CNT_PL_val = 0
    opened_last2Y_CNT_PL_val = 0
    opened_last3Y_CNT_PL_val = 0
    
    opened_last3M_CNT_CD_val = 0
    opened_last6M_CNT_CD_val = 0
    opened_last9M_CNT_CD_val = 0
    opened_last1Y_CNT_CD_val = 0
    opened_last2Y_CNT_CD_val = 0
    opened_last3Y_CNT_CD_val = 0
    
    opened_last3M_CNT_SEL_val = 0
    opened_last6M_CNT_SEL_val = 0
    opened_last9M_CNT_SEL_val = 0
    opened_last1Y_CNT_SEL_val = 0
    opened_last2Y_CNT_SEL_val = 0
    opened_last3Y_CNT_SEL_val = 0
    
    opened_last3M_CNT_RL_val = 0
    opened_last6M_CNT_RL_val = 0
    opened_last9M_CNT_RL_val = 0
    opened_last1Y_CNT_RL_val = 0
    opened_last2Y_CNT_RL_val = 0
    opened_last3Y_CNT_RL_val = 0
    
    opened_last3M_CNT_CV_val = 0
    opened_last6M_CNT_CV_val = 0
    opened_last9M_CNT_CV_val = 0
    opened_last1Y_CNT_CV_val = 0
    opened_last2Y_CNT_CV_val = 0
    opened_last3Y_CNT_CV_val = 0
    
    opened_last3M_CNT_CC_val = 0
    opened_last6M_CNT_CC_val = 0
    opened_last9M_CNT_CC_val = 0
    opened_last1Y_CNT_CC_val = 0
    opened_last2Y_CNT_CC_val = 0
    opened_last3Y_CNT_CC_val = 0
    
    opened_last3M_CNT_RL_val = 0
    opened_last6M_CNT_RL_val = 0
    opened_last9M_CNT_RL_val = 0
    opened_last1Y_CNT_RL_val = 0
    opened_last2Y_CNT_RL_val = 0
    opened_last3Y_CNT_RL_val = 0
    
    opened_last3M_CNT_SCC_val = 0
    opened_last6M_CNT_SCC_val = 0
    opened_last9M_CNT_SCC_val = 0
    opened_last1Y_CNT_SCC_val = 0
    opened_last2Y_CNT_SCC_val = 0
    opened_last3Y_CNT_SCC_val = 0
    
    opened_last3M_CNT_BL_val = 0
    opened_last6M_CNT_BL_val = 0
    opened_last9M_CNT_BL_val = 0
    opened_last1Y_CNT_BL_val = 0
    opened_last2Y_CNT_BL_val = 0
    opened_last3Y_CNT_BL_val = 0
    
    opened_last3M_CNT_MFBL_val = 0
    opened_last6M_CNT_MFBL_val = 0
    opened_last9M_CNT_MFBL_val = 0
    opened_last1Y_CNT_MFBL_val = 0
    opened_last2Y_CNT_MFBL_val = 0
    opened_last3Y_CNT_MFBL_val = 0
    
    opened_last3M_CNT_MFPL_val = 0
    opened_last6M_CNT_MFPL_val = 0
    opened_last9M_CNT_MFPL_val = 0
    opened_last1Y_CNT_MFPL_val = 0
    opened_last2Y_CNT_MFPL_val = 0
    opened_last3Y_CNT_MFPL_val = 0
    

    opened_last3M_CNT_MFHL_val = 0
    opened_last6M_CNT_MFHL_val = 0
    opened_last9M_CNT_MFHL_val = 0
    opened_last1Y_CNT_MFHL_val = 0
    opened_last2Y_CNT_MFHL_val = 0
    opened_last3Y_CNT_MFHL_val = 0
    
    opened_last3M_CNT_MFOT_val = 0
    opened_last6M_CNT_MFOT_val = 0
    opened_last9M_CNT_MFOT_val = 0
    opened_last1Y_CNT_MFOT_val = 0
    opened_last2Y_CNT_MFOT_val = 0
    opened_last3Y_CNT_MFOT_val = 0
    
    opened_last3M_CNT_PLBL_val = 0
    opened_last6M_CNT_PLBL_val = 0
    opened_last9M_CNT_PLBL_val = 0
    opened_last1Y_CNT_PLBL_val = 0
    opened_last2Y_CNT_PLBL_val = 0
    opened_last3Y_CNT_PLBL_val = 0
    
    opened_last3M_CNT_PLRLBL_val = 0
    opened_last6M_CNT_PLRLBL_val = 0
    opened_last9M_CNT_PLRLBL_val = 0
    opened_last1Y_CNT_PLRLBL_val = 0
    opened_last2Y_CNT_PLRLBL_val = 0
    opened_last3Y_CNT_PLRLBL_val = 0
    
    opened_last3M_CNT_OTH_val = 0
    opened_last6M_CNT_OTH_val = 0
    opened_last9M_CNT_OTH_val = 0
    opened_last1Y_CNT_OTH_val = 0
    opened_last2Y_CNT_OTH_val = 0
    opened_last3Y_CNT_OTH_val = 0
    
    opened_last3M_CNT_SEC_val = 0
    opened_last6M_CNT_SEC_val = 0
    opened_last9M_CNT_SEC_val = 0
    opened_last1Y_CNT_SEC_val = 0
    opened_last2Y_CNT_SEC_val = 0
    opened_last3Y_CNT_SEC_val = 0
    
    opened_last3M_CNT_UNSEC_val = 0
    opened_last6M_CNT_UNSEC_val = 0
    opened_last9M_CNT_UNSEC_val = 0
    opened_last1Y_CNT_UNSEC_val = 0
    opened_last2Y_CNT_UNSEC_val = 0
    opened_last3Y_CNT_UNSEC_val = 0
    
    

    
    for j in range(len(data['dateOpenedOrDisbursed'][i])):
        date_before_3M = data['startTime_Date'][i][j] + three_mon_rel
        date_before_6M = data['startTime_Date'][i][j] + six_mon_rel
        date_before_9M = data['startTime_Date'][i][j] + nine_mon_rel
        date_before_1Y = data['startTime_Date'][i][j] + one_year_rel
        date_before_2Y = data['startTime_Date'][i][j] + two_year_rel
        date_before_3Y = data['startTime_Date'][i][j] + three_year_rel
        
        if data['accountType'][i][j] == "HL":
 
            opened_last3M_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            
        if data['accountType'][i][j] == "GL":
            
            opened_last3M_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "AL":
            
            opened_last3M_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "LAS":
            
            opened_last3M_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "PL":
            
            opened_last3M_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "CD":
            
            opened_last3M_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "SEL":
            
            opened_last3M_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "CC":
            
            opened_last3M_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "RL":
            
            opened_last3M_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "CV":
            
            opened_last3M_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "SCC":
            
            opened_last3M_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "BL":
            
            opened_last3M_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        
        if data['accountType'][i][j] == "MFBL":
            
            opened_last3M_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "MFPL":
            
            opened_last3M_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "MFOT":
            
            opened_last3M_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "PLBL":
            
            opened_last3M_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "PLRLBL":
            
            opened_last3M_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "SECFor an applicant, count all the loan accounts which have been opened in last 1 year and gap between the open dates <=3 months":
            
            opened_last3M_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "UNSEC":
            
            opened_last3M_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "OTH":
            
            opened_last3M_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last6M_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last9M_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last1Y_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last2Y_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
            opened_last3Y_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i])
               
         

        
        
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_HL')] = opened_last3M_CNT_HL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_HL')] = opened_last6M_CNT_HL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_HL')] = opened_last9M_CNT_HL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_HL')] = opened_last1Y_CNT_HL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_HL')] = opened_last2Y_CNT_HL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_HL')] = opened_last3Y_CNT_HL_val 
    

    data.iat[i,data.columns.get_loc('opened_last3M_CNT_GL')] = opened_last3M_CNT_GL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_GL')] = opened_last6M_CNT_GL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_GL')] = opened_last9M_CNT_GL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_GL')] = opened_last1Y_CNT_GL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_GL')] = opened_last2Y_CNT_GL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_GL')] = opened_last3Y_CNT_GL_val 
    

    data.iat[i,data.columns.get_loc('opened_last3M_CNT_AL')] = opened_last3M_CNT_AL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_AL')] = opened_last6M_CNT_AL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_AL')] = opened_last9M_CNT_AL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_AL')] = opened_last1Y_CNT_AL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_AL')] = opened_last2Y_CNT_AL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_AL')] = opened_last3Y_CNT_AL_val 
    
    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_LAS')] = opened_last3M_CNT_LAS_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_LAS')] = opened_last6M_CNT_LAS_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_LAS')] = opened_last9M_CNT_LAS_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_LAS')] = opened_last1Y_CNT_LAS_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_LAS')] = opened_last2Y_CNT_LAS_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_LAS')] = opened_last3Y_CNT_LAS_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_PL')] = opened_last3M_CNT_PL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_PL')] = opened_last6M_CNT_PL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_PL')] = opened_last9M_CNT_PL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_PL')] = opened_last1Y_CNT_PL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_PL')] = opened_last2Y_CNT_PL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_PL')] = opened_last3Y_CNT_PL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_CD')] = opened_last3M_CNT_CD_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_CD')] = opened_last6M_CNT_CD_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_CD')] = opened_last9M_CNT_CD_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_CD')] = opened_last1Y_CNT_CD_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_CD')] = opened_last2Y_CNT_CD_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_CD')] = opened_last3Y_CNT_CD_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_SEL')] = opened_last3M_CNT_SEL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_SEL')] = opened_last6M_CNT_SEL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_SEL')] = opened_last9M_CNT_SEL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_SEL')] = opened_last1Y_CNT_SEL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_SEL')] = opened_last2Y_CNT_SEL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_SEL')] = opened_last3Y_CNT_SEL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_CC')] = opened_last3M_CNT_CC_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_CC')] = opened_last6M_CNT_CC_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_CC')] = opened_last9M_CNT_CC_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_CC')] = opened_last1Y_CNT_CC_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_CC')] = opened_last2Y_CNT_CC_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_CC')] = opened_last3Y_CNT_CC_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_RL')] = opened_last3M_CNT_RL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_RL')] = opened_last6M_CNT_RL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_RL')] = opened_last9M_CNT_RL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_RL')] = opened_last1Y_CNT_RL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_RL')] = opened_last2Y_CNT_RL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_RL')] = opened_last3Y_CNT_RL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_CV')] = opened_last3M_CNT_CV_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_CV')] = opened_last6M_CNT_CV_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_CV')] = opened_last9M_CNT_CV_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_CV')] = opened_last1Y_CNT_CV_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_CV')] = opened_last2Y_CNT_CV_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_CV')] = opened_last3Y_CNT_CV_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_SCC')] = opened_last3M_CNT_SCC_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_SCC')] = opened_last6M_CNT_SCC_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_SCC')] = opened_last9M_CNT_SCC_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_SCC')] = opened_last1Y_CNT_SCC_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_SCC')] = opened_last2Y_CNT_SCC_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_SCC')] = opened_last3Y_CNT_SCC_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_BL')] = opened_last3M_CNT_BL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_BL')] = opened_last6M_CNT_BL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_BL')] = opened_last9M_CNT_BL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_BL')] = opened_last1Y_CNT_BL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_BL')] = opened_last2Y_CNT_BL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_BL')] = opened_last3Y_CNT_BL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_MFBL')] = opened_last3M_CNT_MFBL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_MFBL')] = opened_last6M_CNT_MFBL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_MFBL')] = opened_last9M_CNT_MFBL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_MFBL')] = opened_last1Y_CNT_MFBL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_MFBL')] = opened_last2Y_CNT_MFBL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_MFBL')] = opened_last3Y_CNT_MFBL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_MFPL')] = opened_last3M_CNT_MFPL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_MFPL')] = opened_last6M_CNT_MFPL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_MFPL')] = opened_last9M_CNT_MFPL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_MFPL')] = opened_last1Y_CNT_MFPL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_MFPL')] = opened_last2Y_CNT_MFPL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_MFPL')] = opened_last3Y_CNT_MFPL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_MFHL')] = opened_last3M_CNT_MFHL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_MFHL')] = opened_last6M_CNT_MFHL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_MFHL')] = opened_last9M_CNT_MFHL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_MFHL')] = opened_last1Y_CNT_MFHL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_MFHL')] = opened_last2Y_CNT_MFHL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_MFHL')] = opened_last3Y_CNT_MFHL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_MFOT')] = opened_last3M_CNT_MFOT_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_MFOT')] = opened_last6M_CNT_MFOT_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_MFOT')] = opened_last9M_CNT_MFOT_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_MFOT')] = opened_last1Y_CNT_MFOT_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_MFOT')] = opened_last2Y_CNT_MFOT_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_MFOT')] = opened_last3Y_CNT_MFOT_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_PLBL')] = opened_last3M_CNT_PLBL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_PLBL')] = opened_last6M_CNT_PLBL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_PLBL')] = opened_last9M_CNT_PLBL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_PLBL')] = opened_last1Y_CNT_PLBL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_PLBL')] = opened_last2Y_CNT_PLBL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_PLBL')] = opened_last3Y_CNT_PLBL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_PLRLBL')] = opened_last3M_CNT_PLRLBL_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_PLRLBL')] = opened_last6M_CNT_PLRLBL_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_PLRLBL')] = opened_last9M_CNT_PLRLBL_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_PLRLBL')] = opened_last1Y_CNT_PLRLBL_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_PLRLBL')] = opened_last2Y_CNT_PLRLBL_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_PLRLBL')] = opened_last3Y_CNT_PLRLBL_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_SEC')] = opened_last3M_CNT_SEC_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_SEC')] = opened_last6M_CNT_SEC_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_SEC')] = opened_last9M_CNT_SEC_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_SEC')] = opened_last1Y_CNT_SEC_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_SEC')] = opened_last2Y_CNT_SEC_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_SEC')] = opened_last3Y_CNT_SEC_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_UNSEC')] = opened_last3M_CNT_UNSEC_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_UNSEC')] = opened_last6M_CNT_UNSEC_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_UNSEC')] = opened_last9M_CNT_UNSEC_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_UNSEC')] = opened_last1Y_CNT_UNSEC_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_UNSEC')] = opened_last2Y_CNT_UNSEC_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_UNSEC')] = opened_last3Y_CNT_UNSEC_val 
    

    
    data.iat[i,data.columns.get_loc('opened_last3M_CNT_OTH')] = opened_last3M_CNT_OTH_val 
    data.iat[i,data.columns.get_loc('opened_last6M_CNT_OTH')] = opened_last6M_CNT_OTH_val 
    data.iat[i,data.columns.get_loc('opened_last9M_CNT_OTH')] = opened_last9M_CNT_OTH_val 
    data.iat[i,data.columns.get_loc('opened_last1Y_CNT_OTH')] = opened_last1Y_CNT_OTH_val 
    data.iat[i,data.columns.get_loc('opened_last2Y_CNT_OTH')] = opened_last2Y_CNT_OTH_val 
    data.iat[i,data.columns.get_loc('opened_last3Y_CNT_OTH')] = opened_last3Y_CNT_OTH_val 
    

data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened,opened_last3M_CNT,opened_last6M_CNT,opened_last9M_CNT,...,opened_last9M_CNT_SEC,opened_last1Y_CNT_SEC,opened_last2Y_CNT_SEC,opened_last3Y_CNT_SEC,opened_last3M_CNT_UNSEC,opened_last6M_CNT_UNSEC,opened_last9M_CNT_UNSEC,opened_last1Y_CNT_UNSEC,opened_last2Y_CNT_UNSEC,opened_last3Y_CNT_UNSEC
0,25056002948,"[2020-07-28 06:56:21.616000, 2020-07-28 06:56:...","[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...","[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[55, 7, 22, 24, 26, 33, 33, 35, 37, 37, 40, 48...",0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,25057004362,"[2020-07-28 06:39:26.277000, 2020-07-28 06:39:...","[2019-12-27, 2018-12-11]","[NaT, NaT]","[PL, AL]","[2020-07-28, 2020-07-28]","[7, 20]",0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,25065002005,[2020-07-28 07:00:50.530000],[2013-11-28],[2014-04-30],[PLBL],[2020-07-28],[80],0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,25150006776,"[2020-07-28 06:24:14.232000, 2020-07-28 06:24:...","[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...","[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[0, 1, 1, 2, 2, 2, 3, 15, 19, 21, 25, 32, 38]",7,7,7,...,0,0,0,0,0,0,0,0,0,0
4,25244001089,"[2020-07-28 06:34:27.226000, 2020-07-28 06:34:...","[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...","[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[74, 8, 12, 20, 25, 39, 42, 45, 49, 50, 73, 80...",0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [36]:
print(len(data['accountType'][0]))

print(data['accountType'][0])
print(data['dateOpenedOrDisbursed'][0])

23
['HL', 'GL', 'GL', 'GL', 'CD', 'BL', 'BL', 'GL', 'GL', 'GL', 'CD', 'OTH', 'CD', 'GL', 'GL', 'GL', 'CD', 'AL', 'PL', 'PL', 'HL', 'GL', 'HL']
[datetime.date(2016, 1, 11), datetime.date(2019, 12, 28), datetime.date(2018, 9, 29), datetime.date(2018, 7, 25), datetime.date(2018, 6, 5), datetime.date(2017, 11, 9), datetime.date(2017, 10, 17), datetime.date(2017, 8, 29), datetime.date(2017, 7, 11), datetime.date(2017, 6, 29), datetime.date(2017, 3, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 26), datetime.date(2016, 7, 18), datetime.date(2016, 6, 28), datetime.date(2016, 6, 18), datetime.date(2016, 3, 21), datetime.date(2007, 4, 24), datetime.date(2006, 11, 29), datetime.date(2006, 9, 27), datetime.date(2005, 7, 30), datetime.date(2013, 10, 3), datetime.date(2005, 7, 30)]

In [37]:
data2 = data[['_ID','dateOpenedOrDisbursed','opened_last3M_CNT_GL','opened_last3Y_CNT_GL']]
data2.head()

,_ID,dateOpenedOrDisbursed,opened_last3M_CNT_GL,opened_last3Y_CNT_GL
0,25056002948,"[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...",0,4
1,25057004362,"[2019-12-27, 2018-12-11]",0,0
2,25065002005,[2013-11-28],0,0
3,25150006776,"[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...",6,6
4,25244001089,"[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...",0,5

###

In [38]:

d = data.loc[data["_ID"] == "3061CD0134441"]

d[["_ID","dateOpenedOrDisbursed", "accountType","opened_last3Y_CNT_GL", "opened_last1Y_CNT_GL","opened_last3M_CNT_GL","opened_last9M_CNT_GL"]]

,_ID,dateOpenedOrDisbursed,accountType,opened_last3Y_CNT_GL,opened_last1Y_CNT_GL,opened_last3M_CNT_GL,opened_last9M_CNT_GL
251,3061CD0134441,"[2020-05-19, 2020-03-06, 2020-02-19, 2020-02-0...","[GL, GL, GL, AL, GL, CD, CD, CD, RL]",4,3,1,3

In [39]:
print(data["dateClosed"][251])

[NaT, NaT, datetime.date(2020, 5, 14), NaT, NaT, datetime.date(2019, 2, 16), NaT, NaT, NaT]

Extracting Derived time variable (Set 4)
--
For an applicant, ratio of all loan accounts where difference between DateOpened and Login Date is <=3 months to all loan accounts where difference between DateClosed (not null) and Login Date is <=[ (3, 6, 9) months, (1, 2, 3) years] per product group

In [40]:
data['opened_closed_last3M_CNT_PL'] = 0
data['opened_closed_last6M_CNT_PL'] = 0
data['opened_closed_last9M_CNT_PL'] = 0
data['opened_closed_last1Y_CNT_PL'] = 0
data['opened_closed_last2Y_CNT_PL'] = 0
data['opened_closed_last3Y_CNT_PL'] = 0



data['opened_closed_last3M_CNT_HL'] = 0
data['opened_closed_last6M_CNT_HL'] = 0
data['opened_closed_last9M_CNT_HL'] = 0
data['opened_closed_last1Y_CNT_HL'] = 0
data['opened_closed_last2Y_CNT_HL'] = 0
data['opened_closed_last3Y_CNT_HL'] = 0


data['opened_closed_last3M_CNT_GL'] = 0
data['opened_closed_last6M_CNT_GL'] = 0
data['opened_closed_last9M_CNT_GL'] = 0
data['opened_closed_last1Y_CNT_GL'] = 0
data['opened_closed_last2Y_CNT_GL'] = 0
data['opened_closed_last3Y_CNT_GL'] = 0



data['opened_closed_last3M_CNT_AL'] = 0
data['opened_closed_last6M_CNT_AL'] = 0
data['opened_closed_last9M_CNT_AL'] = 0
data['opened_closed_last1Y_CNT_AL'] = 0
data['opened_closed_last2Y_CNT_AL'] = 0
data['opened_closed_last3Y_CNT_AL'] = 0



data['opened_closed_last3M_CNT_SEL'] = 0
data['opened_closed_last6M_CNT_SEL'] = 0
data['opened_closed_last9M_CNT_SEL'] = 0
data['opened_closed_last1Y_CNT_SEL'] = 0
data['opened_closed_last2Y_CNT_SEL'] = 0
data['opened_closed_last3Y_CNT_SEL'] = 0



data['opened_closed_last3M_CNT_LAS'] = 0
data['opened_closed_last6M_CNT_LAS'] = 0
data['opened_closed_last9M_CNT_LAS'] = 0
data['opened_closed_last1Y_CNT_LAS'] = 0
data['opened_closed_last2Y_CNT_LAS'] = 0
data['opened_closed_last3Y_CNT_LAS'] = 0



data['opened_closed_last3M_CNT_CD'] = 0
data['opened_closed_last6M_CNT_CD'] = 0
data['opened_closed_last9M_CNT_CD'] = 0
data['opened_closed_last1Y_CNT_CD'] = 0
data['opened_closed_last2Y_CNT_CD'] = 0
data['opened_closed_last3Y_CNT_CD'] = 0



data['opened_closed_last3M_CNT_CC'] = 0
data['opened_closed_last6M_CNT_CC'] = 0
data['opened_closed_last9M_CNT_CC'] = 0
data['opened_closed_last1Y_CNT_CC'] = 0
data['opened_closed_last2Y_CNT_CC'] = 0
data['opened_closed_last3Y_CNT_CC'] = 0


data['opened_closed_last3M_CNT_RL'] = 0
data['opened_closed_last6M_CNT_RL'] = 0
data['opened_closed_last9M_CNT_RL'] = 0
data['opened_closed_last1Y_CNT_RL'] = 0
data['opened_closed_last2Y_CNT_RL'] = 0
data['opened_closed_last3Y_CNT_RL'] = 0



data['opened_closed_last3M_CNT_CV'] = 0
data['opened_closed_last6M_CNT_CV'] = 0
data['opened_closed_last9M_CNT_CV'] = 0
data['opened_closed_last1Y_CNT_CV'] = 0
data['opened_closed_last2Y_CNT_CV'] = 0
data['opened_closed_last3Y_CNT_CV'] = 0


data['opened_closed_last3M_CNT_SCC'] = 0
data['opened_closed_last6M_CNT_SCC'] = 0
data['opened_closed_last9M_CNT_SCC'] = 0
data['opened_closed_last1Y_CNT_SCC'] = 0
data['opened_closed_last2Y_CNT_SCC'] = 0
data['opened_closed_last3Y_CNT_SCC'] = 0



data['opened_closed_last3M_CNT_BL'] = 0
data['opened_closed_last6M_CNT_BL'] = 0
data['opened_closed_last9M_CNT_BL'] = 0
data['opened_closed_last1Y_CNT_BL'] = 0
data['opened_closed_last2Y_CNT_BL'] = 0
data['opened_closed_last3Y_CNT_BL'] = 0


data['opened_closed_last3M_CNT_MFBL'] = 0
data['opened_closed_last6M_CNT_MFBL'] = 0
data['opened_closed_last9M_CNT_MFBL'] = 0
data['opened_closed_last1Y_CNT_MFBL'] = 0
data['opened_closed_last2Y_CNT_MFBL'] = 0
data['opened_closed_last3Y_CNT_MFBL'] = 0

data['opened_closed_last3M_CNT_MFPL'] = 0
data['opened_closed_last6M_CNT_MFPL'] = 0
data['opened_closed_last9M_CNT_MFPL'] = 0
data['opened_closed_last1Y_CNT_MFPL'] = 0
data['opened_closed_last2Y_CNT_MFPL'] = 0
data['opened_closed_last3Y_CNT_MFPL'] = 0


data['opened_closed_last3M_CNT_MFHL'] = 0
data['opened_closed_last6M_CNT_MFHL'] = 0
data['opened_closed_last9M_CNT_MFHL'] = 0
data['opened_closed_last1Y_CNT_MFHL'] = 0
data['opened_closed_last2Y_CNT_MFHL'] = 0
data['opened_closed_last3Y_CNT_MFHL'] = 0


data['opened_closed_last3M_CNT_MFOT'] = 0
data['opened_closed_last6M_CNT_MFOT'] = 0
data['opened_closed_last9M_CNT_MFOT'] = 0
data['opened_closed_last1Y_CNT_MFOT'] = 0
data['opened_closed_last2Y_CNT_MFOT'] = 0
data['opened_closed_last3Y_CNT_MFOT'] = 0



data['opened_closed_last3M_CNT_OTH'] = 0
data['opened_closed_last6M_CNT_OTH'] = 0
data['opened_closed_last9M_CNT_OTH'] = 0
data['opened_closed_last1Y_CNT_OTH'] = 0
data['opened_closed_last2Y_CNT_OTH'] = 0
data['opened_closed_last3Y_CNT_OTH'] = 0



data['opened_closed_last3M_CNT_PLBL'] = 0
data['opened_closed_last6M_CNT_PLBL'] = 0
data['opened_closed_last9M_CNT_PLBL'] = 0
data['opened_closed_last1Y_CNT_PLBL'] = 0
data['opened_closed_last2Y_CNT_PLBL'] = 0
data['opened_closed_last3Y_CNT_PLBL'] = 0



data['opened_closed_last3M_CNT_PLRLBL'] = 0 
data['opened_closed_last6M_CNT_PLRLBL'] = 0
data['opened_closed_last9M_CNT_PLRLBL'] = 0
data['opened_closed_last1Y_CNT_PLRLBL'] = 0
data['opened_closed_last2Y_CNT_PLRLBL'] = 0
data['opened_closed_last3Y_CNT_PLRLBL'] = 0



data['opened_closed_last3M_CNT_SEC'] = 0
data['opened_closed_last6M_CNT_SEC'] = 0
data['opened_closed_last9M_CNT_SEC'] = 0
data['opened_closed_last1Y_CNT_SEC'] = 0
data['opened_closed_last2Y_CNT_SEC'] = 0
data['opened_closed_last3Y_CNT_SEC'] = 0



data['opened_closed_last3M_CNT_UNSEC'] = 0 
data['opened_closed_last6M_CNT_UNSEC'] = 0
data['opened_closed_last9M_CNT_UNSEC'] = 0
data['opened_closed_last1Y_CNT_UNSEC'] = 0
data['opened_closed_last2Y_CNT_UNSEC'] = 0
data['opened_closed_last3Y_CNT_UNSEC'] = 0

In [41]:
data['opened_closed_last3M_CNT_PL'] = data['opened_closed_last3M_CNT_PL'].astype(object)
data['opened_closed_last6M_CNT_PL'] = data['opened_closed_last6M_CNT_PL'].astype(object)
data['opened_closed_last9M_CNT_PL'] = data['opened_closed_last9M_CNT_PL'].astype(object)
data['opened_closed_last1Y_CNT_PL'] = data['opened_closed_last1Y_CNT_PL'].astype(object)
data['opened_closed_last2Y_CNT_PL'] = data['opened_closed_last2Y_CNT_PL'].astype(object)
data['opened_closed_last3Y_CNT_PL'] = data['opened_closed_last3Y_CNT_PL'].astype(object)



data['opened_closed_last3M_CNT_HL'] = data['opened_closed_last3M_CNT_HL'].astype(object)
data['opened_closed_last6M_CNT_HL'] = data['opened_closed_last6M_CNT_HL'].astype(object)
data['opened_closed_last9M_CNT_HL'] = data['opened_closed_last9M_CNT_HL'].astype(object)
data['opened_closed_last1Y_CNT_HL'] = data['opened_closed_last1Y_CNT_HL'].astype(object)
data['opened_closed_last2Y_CNT_HL'] = data['opened_closed_last2Y_CNT_HL'].astype(object)
data['opened_closed_last3Y_CNT_HL'] = data['opened_closed_last3Y_CNT_HL'].astype(object)


data['opened_closed_last3M_CNT_GL'] = data['opened_closed_last3M_CNT_GL'].astype(object)
data['opened_closed_last6M_CNT_GL'] = data['opened_closed_last6M_CNT_GL'].astype(object)
data['opened_closed_last9M_CNT_GL'] = data['opened_closed_last9M_CNT_GL'].astype(object)
data['opened_closed_last1Y_CNT_GL'] = data['opened_closed_last1Y_CNT_GL'].astype(object)
data['opened_closed_last2Y_CNT_GL'] = data['opened_closed_last2Y_CNT_GL'].astype(object)
data['opened_closed_last3Y_CNT_GL'] = data['opened_closed_last3Y_CNT_GL'].astype(object)



data['opened_closed_last3M_CNT_AL'] = data['opened_closed_last3M_CNT_AL'].astype(object)
data['opened_closed_last6M_CNT_AL'] = data['opened_closed_last6M_CNT_AL'].astype(object)
data['opened_closed_last9M_CNT_AL'] = data['opened_closed_last9M_CNT_AL'].astype(object)
data['opened_closed_last1Y_CNT_AL'] = data['opened_closed_last1Y_CNT_AL'].astype(object)
data['opened_closed_last2Y_CNT_AL'] = data['opened_closed_last2Y_CNT_AL'].astype(object)
data['opened_closed_last3Y_CNT_AL'] = data['opened_closed_last3Y_CNT_AL'].astype(object)


data['opened_closed_last3M_CNT_SEL'] = data['opened_closed_last3M_CNT_SEL'].astype(object)
data['opened_closed_last6M_CNT_SEL'] = data['opened_closed_last6M_CNT_SEL'].astype(object)
data['opened_closed_last9M_CNT_SEL'] = data['opened_closed_last9M_CNT_SEL'].astype(object)
data['opened_closed_last1Y_CNT_SEL'] = data['opened_closed_last1Y_CNT_SEL'].astype(object)
data['opened_closed_last2Y_CNT_SEL'] = data['opened_closed_last2Y_CNT_SEL'].astype(object)
data['opened_closed_last3Y_CNT_SEL'] = data['opened_closed_last3Y_CNT_SEL'].astype(object)



data['opened_closed_last3M_CNT_LAS'] = data['opened_closed_last3M_CNT_LAS'].astype(object)
data['opened_closed_last6M_CNT_LAS'] = data['opened_closed_last6M_CNT_LAS'].astype(object)
data['opened_closed_last9M_CNT_LAS'] = data['opened_closed_last9M_CNT_LAS'].astype(object)
data['opened_closed_last1Y_CNT_LAS'] = data['opened_closed_last1Y_CNT_LAS'].astype(object)
data['opened_closed_last2Y_CNT_LAS'] = data['opened_closed_last2Y_CNT_LAS'].astype(object)
data['opened_closed_last3Y_CNT_LAS'] = data['opened_closed_last3Y_CNT_LAS'].astype(object)



data['opened_closed_last3M_CNT_CD'] = data['opened_closed_last3M_CNT_CD'].astype(object)
data['opened_closed_last6M_CNT_CD'] = data['opened_closed_last6M_CNT_CD'].astype(object)
data['opened_closed_last9M_CNT_CD'] = data['opened_closed_last9M_CNT_CD'].astype(object)
data['opened_closed_last1Y_CNT_CD'] = data['opened_closed_last1Y_CNT_CD'].astype(object)
data['opened_closed_last2Y_CNT_CD'] = data['opened_closed_last2Y_CNT_CD'].astype(object)
data['opened_closed_last3Y_CNT_CD'] = data['opened_closed_last3Y_CNT_CD'].astype(object)



data['opened_closed_last3M_CNT_CC'] = data['opened_closed_last3M_CNT_CC'].astype(object)
data['opened_closed_last6M_CNT_CC'] = data['opened_closed_last6M_CNT_CC'].astype(object)
data['opened_closed_last9M_CNT_CC'] = data['opened_closed_last9M_CNT_CC'].astype(object)
data['opened_closed_last1Y_CNT_CC'] = data['opened_closed_last1Y_CNT_CC'].astype(object)
data['opened_closed_last2Y_CNT_CC'] = data['opened_closed_last2Y_CNT_CC'].astype(object)
data['opened_closed_last3Y_CNT_CC'] = data['opened_closed_last3Y_CNT_CC'].astype(object)


data['opened_closed_last3M_CNT_RL'] = data['opened_closed_last3M_CNT_RL'].astype(object)
data['opened_closed_last6M_CNT_RL'] = data['opened_closed_last6M_CNT_RL'].astype(object)
data['opened_closed_last9M_CNT_RL'] = data['opened_closed_last9M_CNT_RL'].astype(object)
data['opened_closed_last1Y_CNT_RL'] = data['opened_closed_last1Y_CNT_RL'].astype(object)
data['opened_closed_last2Y_CNT_RL'] = data['opened_closed_last2Y_CNT_RL'].astype(object)
data['opened_closed_last3Y_CNT_RL'] = data['opened_closed_last3Y_CNT_RL'].astype(object)



data['opened_closed_last3M_CNT_CV'] = data['opened_closed_last3M_CNT_CV'].astype(object)
data['opened_closed_last6M_CNT_CV'] = data['opened_closed_last6M_CNT_CV'].astype(object)
data['opened_closed_last9M_CNT_CV'] = data['opened_closed_last9M_CNT_CV'].astype(object)
data['opened_closed_last1Y_CNT_CV'] = data['opened_closed_last1Y_CNT_CV'].astype(object)
data['opened_closed_last2Y_CNT_CV'] = data['opened_closed_last2Y_CNT_CV'].astype(object)
data['opened_closed_last3Y_CNT_CV'] = data['opened_closed_last3Y_CNT_CV'].astype(object)


data['opened_closed_last3M_CNT_SCC'] = data['opened_closed_last3M_CNT_SCC'].astype(object)
data['opened_closed_last6M_CNT_SCC'] = data['opened_closed_last6M_CNT_SCC'].astype(object)
data['opened_closed_last9M_CNT_SCC'] = data['opened_closed_last9M_CNT_SCC'].astype(object)
data['opened_closed_last1Y_CNT_SCC'] = data['opened_closed_last1Y_CNT_SCC'].astype(object)
data['opened_closed_last2Y_CNT_SCC'] = data['opened_closed_last2Y_CNT_SCC'].astype(object)
data['opened_closed_last3Y_CNT_SCC'] = data['opened_closed_last3Y_CNT_SCC'].astype(object)



data['opened_closed_last3M_CNT_BL'] = data['opened_closed_last3M_CNT_BL'].astype(object)
data['opened_closed_last6M_CNT_BL'] = data['opened_closed_last6M_CNT_BL'].astype(object)
data['opened_closed_last9M_CNT_BL'] = data['opened_closed_last9M_CNT_BL'].astype(object)
data['opened_closed_last1Y_CNT_BL'] = data['opened_closed_last1Y_CNT_BL'].astype(object)
data['opened_closed_last2Y_CNT_BL'] = data['opened_closed_last2Y_CNT_BL'].astype(object)
data['opened_closed_last3Y_CNT_BL'] = data['opened_closed_last3Y_CNT_BL'].astype(object)


data['opened_closed_last3M_CNT_MFBL'] = data['opened_closed_last3M_CNT_MFBL'].astype(object)
data['opened_closed_last6M_CNT_MFBL'] = data['opened_closed_last6M_CNT_MFBL'].astype(object)
data['opened_closed_last9M_CNT_MFBL'] = data['opened_closed_last9M_CNT_MFBL'].astype(object)
data['opened_closed_last1Y_CNT_MFBL'] = data['opened_closed_last1Y_CNT_MFBL'].astype(object)
data['opened_closed_last2Y_CNT_MFBL'] = data['opened_closed_last2Y_CNT_MFBL'].astype(object)
data['opened_closed_last3Y_CNT_MFBL'] = data['opened_closed_last3Y_CNT_MFBL'].astype(object)



data['opened_closed_last3M_CNT_MFPL'] = data['opened_closed_last3M_CNT_MFPL'].astype(object)
data['opened_closed_last6M_CNT_MFPL'] = data['opened_closed_last6M_CNT_MFPL'].astype(object)
data['opened_closed_last9M_CNT_MFPL'] = data['opened_closed_last9M_CNT_MFPL'].astype(object)
data['opened_closed_last1Y_CNT_MFPL'] = data['opened_closed_last1Y_CNT_MFPL'].astype(object)
data['opened_closed_last2Y_CNT_MFPL'] = data['opened_closed_last2Y_CNT_MFPL'].astype(object)
data['opened_closed_last3Y_CNT_MFPL'] = data['opened_closed_last3Y_CNT_MFPL'].astype(object)



data['opened_closed_last3M_CNT_MFHL'] = data['opened_closed_last3M_CNT_MFHL'].astype(object)
data['opened_closed_last6M_CNT_MFHL'] = data['opened_closed_last6M_CNT_MFHL'].astype(object)
data['opened_closed_last9M_CNT_MFHL'] = data['opened_closed_last9M_CNT_MFHL'].astype(object)
data['opened_closed_last1Y_CNT_MFHL'] = data['opened_closed_last1Y_CNT_MFHL'].astype(object)
data['opened_closed_last2Y_CNT_MFHL'] = data['opened_closed_last2Y_CNT_MFHL'].astype(object)
data['opened_closed_last3Y_CNT_MFHL'] = data['opened_closed_last3Y_CNT_MFHL'].astype(object)


data['opened_closed_last3M_CNT_MFOT'] = data['opened_closed_last3M_CNT_MFOT'].astype(object)
data['opened_closed_last6M_CNT_MFOT'] = data['opened_closed_last6M_CNT_MFOT'].astype(object)
data['opened_closed_last9M_CNT_MFOT'] = data['opened_closed_last9M_CNT_MFOT'].astype(object)
data['opened_closed_last1Y_CNT_MFOT'] = data['opened_closed_last1Y_CNT_MFOT'].astype(object)
data['opened_closed_last2Y_CNT_MFOT'] = data['opened_closed_last2Y_CNT_MFOT'].astype(object)
data['opened_closed_last3Y_CNT_MFOT'] = data['opened_closed_last3Y_CNT_MFOT'].astype(object)



data['opened_closed_last3M_CNT_OTH'] = data['opened_closed_last3M_CNT_OTH'].astype(object)
data['opened_closed_last6M_CNT_OTH'] = data['opened_closed_last6M_CNT_OTH'].astype(object)
data['opened_closed_last9M_CNT_OTH'] = data['opened_closed_last9M_CNT_OTH'].astype(object)
data['opened_closed_last1Y_CNT_OTH'] = data['opened_closed_last1Y_CNT_OTH'].astype(object)
data['opened_closed_last2Y_CNT_OTH'] = data['opened_closed_last2Y_CNT_OTH'].astype(object)
data['opened_closed_last3Y_CNT_OTH'] = data['opened_closed_last3Y_CNT_OTH'].astype(object)



data['opened_closed_last3M_CNT_PLBL'] = data['opened_closed_last3M_CNT_PLBL'].astype(object)
data['opened_closed_last6M_CNT_PLBL'] = data['opened_closed_last6M_CNT_PLBL'].astype(object)
data['opened_closed_last9M_CNT_PLBL'] = data['opened_closed_last9M_CNT_PLBL'].astype(object)
data['opened_closed_last1Y_CNT_PLBL'] = data['opened_closed_last1Y_CNT_PLBL'].astype(object)
data['opened_closed_last2Y_CNT_PLBL'] = data['opened_closed_last2Y_CNT_PLBL'].astype(object)
data['opened_closed_last3Y_CNT_PLBL'] = data['opened_closed_last3Y_CNT_PLBL'].astype(object)



data['opened_closed_last3M_CNT_PLRLBL'] = data['opened_closed_last3M_CNT_PLRLBL'].astype(object)
data['opened_closed_last6M_CNT_PLRLBL'] = data['opened_closed_last6M_CNT_PLRLBL'].astype(object)
data['opened_closed_last9M_CNT_PLRLBL'] = data['opened_closed_last9M_CNT_PLRLBL'].astype(object)
data['opened_closed_last1Y_CNT_PLRLBL'] = data['opened_closed_last1Y_CNT_PLRLBL'].astype(object)
data['opened_closed_last2Y_CNT_PLRLBL'] = data['opened_closed_last2Y_CNT_PLRLBL'].astype(object)
data['opened_closed_last3Y_CNT_PLRLBL'] = data['opened_closed_last3Y_CNT_PLRLBL'].astype(object)



data['opened_closed_last3M_CNT_SEC'] = data['opened_closed_last3M_CNT_SEC'].astype(object)
data['opened_closed_last6M_CNT_SEC'] = data['opened_closed_last6M_CNT_SEC'].astype(object)
data['opened_closed_last9M_CNT_SEC'] = data['opened_closed_last9M_CNT_SEC'].astype(object)
data['opened_closed_last1Y_CNT_SEC'] = data['opened_closed_last1Y_CNT_SEC'].astype(object)
data['opened_closed_last2Y_CNT_SEC'] = data['opened_closed_last2Y_CNT_SEC'].astype(object)
data['opened_closed_last3Y_CNT_SEC'] = data['opened_closed_last3Y_CNT_SEC'].astype(object)



data['opened_closed_last3M_CNT_UNSEC'] = data['opened_closed_last3M_CNT_UNSEC'].astype(object)
data['opened_closed_last6M_CNT_UNSEC'] = data['opened_closed_last6M_CNT_UNSEC'].astype(object)
data['opened_closed_last9M_CNT_UNSEC'] = data['opened_closed_last9M_CNT_UNSEC'].astype(object)
data['opened_closed_last1Y_CNT_UNSEC'] = data['opened_closed_last1Y_CNT_UNSEC'].astype(object)
data['opened_closed_last2Y_CNT_UNSEC'] = data['opened_closed_last2Y_CNT_UNSEC'].astype(object)
data['opened_closed_last3Y_CNT_UNSEC'] = data['opened_closed_last3Y_CNT_UNSEC'].astype(object)

In [42]:
for i in range(data.shape[0]):
    opened_closed_last3M_CNT_HL_val = 0
    opened_closed_last6M_CNT_HL_val = 0
    opened_closed_last9M_CNT_HL_val = 0
    opened_closed_last1Y_CNT_HL_val = 0
    opened_closed_last2Y_CNT_HL_val = 0
    opened_closed_last3Y_CNT_HL_val = 0
    
    opened_closed_last3M_CNT_GL_val = 0
    opened_closed_last6M_CNT_GL_val = 0
    opened_closed_last9M_CNT_GL_val = 0
    opened_closed_last1Y_CNT_GL_val = 0
    opened_closed_last2Y_CNT_GL_val = 0
    opened_closed_last3Y_CNT_GL_val = 0
    
    opened_closed_last3M_CNT_AL_val = 0
    opened_closed_last6M_CNT_AL_val = 0
    opened_closed_last9M_CNT_AL_val = 0
    opened_closed_last1Y_CNT_AL_val = 0
    opened_closed_last2Y_CNT_AL_val = 0
    opened_closed_last3Y_CNT_AL_val = 0
    
    opened_closed_last3M_CNT_LAS_val = 0
    opened_closed_last6M_CNT_LAS_val = 0
    opened_closed_last9M_CNT_LAS_val = 0
    opened_closed_last1Y_CNT_LAS_val = 0
    opened_closed_last2Y_CNT_LAS_val = 0
    opened_closed_last3Y_CNT_LAS_val = 0
    
    opened_closed_last3M_CNT_PL_val = 0
    opened_closed_last6M_CNT_PL_val = 0
    opened_closed_last9M_CNT_PL_val = 0
    opened_closed_last1Y_CNT_PL_val = 0
    opened_closed_last2Y_CNT_PL_val = 0
    opened_closed_last3Y_CNT_PL_val = 0
    
    opened_closed_last3M_CNT_CD_val = 0
    opened_closed_last6M_CNT_CD_val = 0
    opened_closed_last9M_CNT_CD_val = 0
    opened_closed_last1Y_CNT_CD_val = 0
    opened_closed_last2Y_CNT_CD_val = 0
    opened_closed_last3Y_CNT_CD_val = 0
    
    opened_closed_last3M_CNT_SEL_val = 0
    opened_closed_last6M_CNT_SEL_val = 0
    opened_closed_last9M_CNT_SEL_val = 0
    opened_closed_last1Y_CNT_SEL_val = 0
    opened_closed_last2Y_CNT_SEL_val = 0
    opened_closed_last3Y_CNT_SEL_val = 0
    
    opened_closed_last3M_CNT_RL_val = 0
    opened_closed_last6M_CNT_RL_val = 0
    opened_closed_last9M_CNT_RL_val = 0
    opened_closed_last1Y_CNT_RL_val = 0
    opened_closed_last2Y_CNT_RL_val = 0
    opened_closed_last3Y_CNT_RL_val = 0
    
    opened_closed_last3M_CNT_CV_val = 0
    opened_closed_last6M_CNT_CV_val = 0
    opened_closed_last9M_CNT_CV_val = 0
    opened_closed_last1Y_CNT_CV_val = 0
    opened_closed_last2Y_CNT_CV_val = 0
    opened_closed_last3Y_CNT_CV_val = 0
    
    opened_closed_last3M_CNT_CC_val = 0
    opened_closed_last6M_CNT_CC_val = 0
    opened_closed_last9M_CNT_CC_val = 0
    opened_closed_last1Y_CNT_CC_val = 0
    opened_closed_last2Y_CNT_CC_val = 0
    opened_closed_last3Y_CNT_CC_val = 0
    
    opened_closed_last3M_CNT_RL_val = 0
    opened_closed_last6M_CNT_RL_val = 0
    opened_closed_last9M_CNT_RL_val = 0
    opened_closed_last1Y_CNT_RL_val = 0
    opened_closed_last2Y_CNT_RL_val = 0
    opened_closed_last3Y_CNT_RL_val = 0
    
    opened_closed_last3M_CNT_SCC_val = 0
    opened_closed_last6M_CNT_SCC_val = 0
    opened_closed_last9M_CNT_SCC_val = 0
    opened_closed_last1Y_CNT_SCC_val = 0
    opened_closed_last2Y_CNT_SCC_val = 0
    opened_closed_last3Y_CNT_SCC_val = 0
    
    opened_closed_last3M_CNT_BL_val = 0
    opened_closed_last6M_CNT_BL_val = 0
    opened_closed_last9M_CNT_BL_val = 0
    opened_closed_last1Y_CNT_BL_val = 0
    opened_closed_last2Y_CNT_BL_val = 0
    opened_closed_last3Y_CNT_BL_val = 0
    
    opened_closed_last3M_CNT_MFBL_val = 0
    opened_closed_last6M_CNT_MFBL_val = 0
    opened_closed_last9M_CNT_MFBL_val = 0
    opened_closed_last1Y_CNT_MFBL_val = 0
    opened_closed_last2Y_CNT_MFBL_val = 0
    opened_closed_last3Y_CNT_MFBL_val = 0
    
    opened_closed_last3M_CNT_MFPL_val = 0
    opened_closed_last6M_CNT_MFPL_val = 0
    opened_closed_last9M_CNT_MFPL_val = 0
    opened_closed_last1Y_CNT_MFPL_val = 0
    opened_closed_last2Y_CNT_MFPL_val = 0
    opened_closed_last3Y_CNT_MFPL_val = 0
    

    opened_closed_last3M_CNT_MFHL_val = 0
    opened_closed_last6M_CNT_MFHL_val = 0
    opened_closed_last9M_CNT_MFHL_val = 0
    opened_closed_last1Y_CNT_MFHL_val = 0
    opened_closed_last2Y_CNT_MFHL_val = 0
    opened_closed_last3Y_CNT_MFHL_val = 0
    
    opened_closed_last3M_CNT_MFOT_val = 0
    opened_closed_last6M_CNT_MFOT_val = 0
    opened_closed_last9M_CNT_MFOT_val = 0
    opened_closed_last1Y_CNT_MFOT_val = 0
    opened_closed_last2Y_CNT_MFOT_val = 0
    opened_closed_last3Y_CNT_MFOT_val = 0
    
    opened_closed_last3M_CNT_PLBL_val = 0
    opened_closed_last6M_CNT_PLBL_val = 0
    opened_closed_last9M_CNT_PLBL_val = 0
    opened_closed_last1Y_CNT_PLBL_val = 0
    opened_closed_last2Y_CNT_PLBL_val = 0
    opened_closed_last3Y_CNT_PLBL_val = 0
    
    opened_closed_last3M_CNT_PLRLBL_val = 0
    opened_closed_last6M_CNT_PLRLBL_val = 0
    opened_closed_last9M_CNT_PLRLBL_val = 0
    opened_closed_last1Y_CNT_PLRLBL_val = 0
    opened_closed_last2Y_CNT_PLRLBL_val = 0
    opened_closed_last3Y_CNT_PLRLBL_val = 0
    
    opened_closed_last3M_CNT_OTH_val = 0
    opened_closed_last6M_CNT_OTH_val = 0
    opened_closed_last9M_CNT_OTH_val = 0
    opened_closed_last1Y_CNT_OTH_val = 0
    opened_closed_last2Y_CNT_OTH_val = 0
    opened_closed_last3Y_CNT_OTH_val = 0
    
    opened_closed_last3M_CNT_SEC_val = 0
    opened_closed_last6M_CNT_SEC_val = 0
    opened_closed_last9M_CNT_SEC_val = 0
    opened_closed_last1Y_CNT_SEC_val = 0
    opened_closed_last2Y_CNT_SEC_val = 0
    opened_closed_last3Y_CNT_SEC_val = 0
    
    opened_closed_last3M_CNT_UNSEC_val = 0
    opened_closed_last6M_CNT_UNSEC_val = 0
    opened_closed_last9M_CNT_UNSEC_val = 0
    opened_closed_last1Y_CNT_UNSEC_val = 0
    opened_closed_last2Y_CNT_UNSEC_val = 0
    opened_closed_last3Y_CNT_UNSEC_val = 0
    
    

    
    for j in range(len(data['dateClosed'][i])):
        date_before_3M = data['startTime_Date'][i][j] + three_mon_rel
        date_before_6M = data['startTime_Date'][i][j] + six_mon_rel
        date_before_9M = data['startTime_Date'][i][j] + nine_mon_rel
        date_before_1Y = data['startTime_Date'][i][j] + one_year_rel
        date_before_2Y = data['startTime_Date'][i][j] + two_year_rel
        date_before_3Y = data['startTime_Date'][i][j] + three_year_rel
        
        if data['accountType'][i][j] == "HL":
 
            opened_closed_last3M_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_HL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
            
        if data['accountType'][i][j] == "GL":
            
            opened_closed_last3M_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_GL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "AL":
            
            opened_closed_last3M_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_AL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "LAS":
            
            opened_closed_last3M_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_LAS_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "PL":
            
            opened_closed_last3M_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_PL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "CD":
            
            opened_closed_last3M_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_CD_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "SEL":
            
            opened_closed_last3M_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_SEL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "CC":
            
            opened_closed_last3M_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_CC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "RL":
            
            opened_closed_last3M_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_RL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "CV":
            
            opened_closed_last3M_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_CV_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "SCC":
            
            opened_closed_last3M_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_SCC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "BL":
            
            opened_closed_last3M_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_BL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        
        if data['accountType'][i][j] == "MFBL":
            
            opened_closed_last3M_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_MFBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        
        if data['accountType'][i][j] == "MFPL":
            
            opened_closed_last3M_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_MFPL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "MFOT":
            
            opened_closed_last3M_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_MFOT_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "PLBL":
            
            opened_closed_last3M_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_PLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "PLRLBL":
            
            opened_closed_last3M_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_PLRLBL_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "SEC":
            
            opened_closed_last3M_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_SEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "UNSEC":
            
            opened_closed_last3M_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_UNSEC_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])
               
        if data['accountType'][i][j] == "OTH":
            
            opened_closed_last3M_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last6M_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_6M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last9M_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_9M, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last1Y_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last2Y_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateClosed'][i], data['accountType'][i])
            opened_closed_last3Y_CNT_OTH_val = search_dt_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateClosed'][i], data['accountType'][i])

            

        
    try:    
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_HL')] = data['opened_last3M_CNT_HL'][i] / opened_closed_last3M_CNT_HL_val  
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_HL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_HL')] = data['opened_last6M_CNT_HL'][i] / opened_closed_last6M_CNT_HL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_HL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_HL')] = data['opened_last9M_CNT_HL'][i] / opened_closed_last9M_CNT_HL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_HL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_HL')] = data['opened_last1Y_CNT_HL'][i] / opened_closed_last1Y_CNT_HL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_HL')] = "NaN"
        
    try:    
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_HL')] = data['opened_last2Y_CNT_HL'][i] / opened_closed_last2Y_CNT_HL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_HL')] = "NaN"
    
    try:    
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_HL')] = data['opened_last3Y_CNT_HL'][i] / opened_closed_last3Y_CNT_HL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_HL')] = "NaN"

    try:    
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_GL')] = data['opened_last3M_CNT_GL'][i] / opened_closed_last3M_CNT_GL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_GL')] = "NaN"
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_GL')] = data['opened_last6M_CNT_GL'][i] / opened_closed_last6M_CNT_GL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_GL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_GL')] = data['opened_last9M_CNT_GL'][i] / opened_closed_last9M_CNT_GL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_GL')] = "NaN"
    
    try:    
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_GL')] = data['opened_last1Y_CNT_GL'][i] / opened_closed_last1Y_CNT_GL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_GL')] = "NaN"
    
    try:    
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_GL')] = data['opened_last2Y_CNT_GL'][i] / opened_closed_last2Y_CNT_GL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_GL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_GL')] = data['opened_last3Y_CNT_GL'][i] / opened_closed_last3Y_CNT_GL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_GL')] = "NaN"


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_AL')] = data['opened_last3M_CNT_AL'][i] / opened_closed_last3M_CNT_AL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_AL')] = "NaN" 
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_AL')] = data['opened_last6M_CNT_AL'][i] / opened_closed_last6M_CNT_AL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_AL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_AL')] = data['opened_last9M_CNT_AL'][i] / opened_closed_last9M_CNT_AL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_AL')] = "NaN" 
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_AL')] = data['opened_last1Y_CNT_AL'][i] / opened_closed_last1Y_CNT_AL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_AL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_AL')] = data['opened_last2Y_CNT_AL'][i] / opened_closed_last2Y_CNT_AL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_AL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_AL')] = data['opened_last3Y_CNT_AL'][i] / opened_closed_last3Y_CNT_AL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_AL')] = "NaN"
    

    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_LAS')] = data['opened_last3M_CNT_LAS'][i] / opened_closed_last3M_CNT_LAS_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_LAS')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_LAS')] = data['opened_last6M_CNT_LAS'][i] / opened_closed_last6M_CNT_LAS_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_LAS')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_LAS')] = data['opened_last9M_CNT_LAS'][i] / opened_closed_last9M_CNT_LAS_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_LAS')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_LAS')] = data['opened_last1Y_CNT_LAS'][i] / opened_closed_last1Y_CNT_LAS_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_LAS')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_LAS')] = data['opened_last2Y_CNT_LAS'][i] / opened_closed_last2Y_CNT_LAS_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_LAS')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_LAS')] = data['opened_last3Y_CNT_LAS'][i] / opened_closed_last3Y_CNT_LAS_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_LAS')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_PL')] = data['opened_last3M_CNT_PL'][i] / opened_closed_last3M_CNT_PL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_PL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_PL')] = data['opened_last6M_CNT_PL'][i] / opened_closed_last6M_CNT_PL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_PL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_PL')] = data['opened_last9M_CNT_PL'][i] / opened_closed_last9M_CNT_PL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_PL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_PL')] = data['opened_last1Y_CNT_PL'][i] / opened_closed_last1Y_CNT_PL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_PL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_PL')] = data['opened_last2Y_CNT_PL'][i] / opened_closed_last2Y_CNT_PL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_PL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_PL')] = data['opened_last3Y_CNT_PL'][i] / opened_closed_last3Y_CNT_PL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_PL')] = "NaN"
    
    

    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_CD')] = data['opened_last3M_CNT_CD'][i] / opened_closed_last3M_CNT_CD_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_CD')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_CD')] = data['opened_last6M_CNT_CD'][i] / opened_closed_last6M_CNT_CD_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_CD')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_CD')] = data['opened_last9M_CNT_CD'][i] / opened_closed_last9M_CNT_CD_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_CD')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_CD')] = data['opened_last1Y_CNT_CD'][i] / opened_closed_last1Y_CNT_CD_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_CD')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_CD')] = data['opened_last2Y_CNT_CD'][i] / opened_closed_last2Y_CNT_CD_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_CD')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_CD')] = data['opened_last3Y_CNT_CD'][i] / opened_closed_last3Y_CNT_CD_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_CD')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_SEL')] = data['opened_last3M_CNT_SEL'][i] / opened_closed_last3M_CNT_SEL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_SEL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_SEL')] = data['opened_last6M_CNT_SEL'][i] / opened_closed_last6M_CNT_SEL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_SEL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_SEL')] = data['opened_last9M_CNT_SEL'][i] / opened_closed_last9M_CNT_SEL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_SEL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_SEL')] = data['opened_last1Y_CNT_SEL'][i] / opened_closed_last1Y_CNT_SEL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_SEL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_SEL')] = data['opened_last2Y_CNT_SEL'][i] / opened_closed_last2Y_CNT_SEL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_SEL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_SEL')] = data['opened_last3Y_CNT_SEL'][i] / opened_closed_last3Y_CNT_SEL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_SEL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_CC')] = data['opened_last3M_CNT_CC'][i] / opened_closed_last3M_CNT_CC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_CC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_CC')] = data['opened_last6M_CNT_CC'][i] / opened_closed_last6M_CNT_CC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_CC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_CC')] = data['opened_last9M_CNT_CC'][i] / opened_closed_last9M_CNT_CC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_CC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_CC')] = data['opened_last1Y_CNT_CC'][i] / opened_closed_last1Y_CNT_CC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_CC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_CC')] = data['opened_last2Y_CNT_CC'][i] / opened_closed_last2Y_CNT_CC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_CC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_CC')] = data['opened_last3Y_CNT_CC'][i] / opened_closed_last3Y_CNT_CC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_CC')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_RL')] = data['opened_last3M_CNT_RL'][i] / opened_closed_last3M_CNT_RL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_RL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_RL')] = data['opened_last6M_CNT_RL'][i] / opened_closed_last6M_CNT_RL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_RL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_RL')] = data['opened_last9M_CNT_RL'][i] / opened_closed_last9M_CNT_RL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_RL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_RL')] = data['opened_last1Y_CNT_RL'][i] / opened_closed_last1Y_CNT_RL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_RL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_RL')] = data['opened_last2Y_CNT_RL'][i] / opened_closed_last2Y_CNT_RL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_RL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_RL')] = data['opened_last3Y_CNT_RL'][i] / opened_closed_last3Y_CNT_RL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_RL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_CV')] = data['opened_last3M_CNT_CV'][i] / opened_closed_last3M_CNT_CV_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_CV')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_CV')] = data['opened_last6M_CNT_CV'][i] / opened_closed_last6M_CNT_CV_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_CV')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_CV')] = data['opened_last9M_CNT_CV'][i] / opened_closed_last9M_CNT_CV_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_CV')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_CV')] = data['opened_last1Y_CNT_CV'][i] / opened_closed_last1Y_CNT_CV_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_CV')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_CV')] = data['opened_last2Y_CNT_CV'][i] / opened_closed_last2Y_CNT_CV_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_CV')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_CV')] = data['opened_last3Y_CNT_CV'][i] / opened_closed_last3Y_CNT_CV_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_CV')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_SCC')] = data['opened_last3M_CNT_SCC'][i] / opened_closed_last3M_CNT_SCC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_SCC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_SCC')] = data['opened_last6M_CNT_SCC'][i] / opened_closed_last6M_CNT_SCC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_SCC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_SCC')] = data['opened_last9M_CNT_SCC'][i] / opened_closed_last9M_CNT_SCC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_SCC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_SCC')] = data['opened_last1Y_CNT_SCC'][i] / opened_closed_last1Y_CNT_SCC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_SCC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_SCC')] = data['opened_last2Y_CNT_SCC'][i] / opened_closed_last2Y_CNT_SCC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_SCC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_SCC')] = data['opened_last3Y_CNT_SCC'][i] / opened_closed_last3Y_CNT_SCC_val 

    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_SCC')] = "NaN"
    
    
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_BL')] = data['opened_last3M_CNT_BL'][i] / opened_closed_last3M_CNT_BL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_BL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_BL')] = data['opened_last6M_CNT_BL'][i] / opened_closed_last6M_CNT_BL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_BL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_BL')] = data['opened_last9M_CNT_BL'][i] / opened_closed_last9M_CNT_BL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_BL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_BL')] = data['opened_last1Y_CNT_BL'][i] / opened_closed_last1Y_CNT_BL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_BL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_BL')] = data['opened_last2Y_CNT_BL'][i] / opened_closed_last2Y_CNT_BL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_BL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_BL')] = data['opened_last3Y_CNT_BL'][i] / opened_closed_last3Y_CNT_BL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_BL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFBL')] = data['opened_last3M_CNT_MFBL'][i] / opened_closed_last3M_CNT_MFBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFBL')] = data['opened_last6M_CNT_MFBL'][i] / opened_closed_last6M_CNT_MFBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFBL')] = data['opened_last9M_CNT_MFBL'][i] / opened_closed_last9M_CNT_MFBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFBL')] = data['opened_last1Y_CNT_MFBL'][i] / opened_closed_last1Y_CNT_MFBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFBL')] = data['opened_last2Y_CNT_MFBL'][i] / opened_closed_last2Y_CNT_MFBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFBL')] = data['opened_last3Y_CNT_MFBL'][i] / opened_closed_last3Y_CNT_MFBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFBL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFPL')] = data['opened_last3M_CNT_MFPL'][i] / opened_closed_last3M_CNT_MFPL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFPL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFPL')] = data['opened_last6M_CNT_MFPL'][i] / opened_closed_last6M_CNT_MFPL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFPL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFPL')] = data['opened_last9M_CNT_MFPL'][i] / opened_closed_last9M_CNT_MFPL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFPL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFPL')] = data['opened_last1Y_CNT_MFPL'][i] / opened_closed_last1Y_CNT_MFPL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFPL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFPL')] = data['opened_last2Y_CNT_MFPL'][i] / opened_closed_last2Y_CNT_MFPL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFPL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFPL')] = data['opened_last3Y_CNT_MFPL'][i] / opened_closed_last3Y_CNT_MFPL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFPL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFHL')] = data['opened_last3M_CNT_MFHL'][i] / opened_closed_last3M_CNT_MFHL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFHL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFHL')] = data['opened_last6M_CNT_MFHL'][i] / opened_closed_last6M_CNT_MFHL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFHL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFHL')] = data['opened_last9M_CNT_MFHL'][i] / opened_closed_last9M_CNT_MFHL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFHL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFHL')] = data['opened_last1Y_CNT_MFHL'][i] / opened_closed_last1Y_CNT_MFHL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFHL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFHL')] = data['opened_last2Y_CNT_MFHL'][i] / opened_closed_last2Y_CNT_MFHL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFHL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFHL')] = data['opened_last3Y_CNT_MFHL'][i] / opened_closed_last3Y_CNT_MFHL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFHL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFOT')] = data['opened_last3M_CNT_MFOT'][i] / opened_closed_last3M_CNT_MFOT_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_MFOT')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFOT')] = data['opened_last6M_CNT_MFOT'][i] / opened_closed_last6M_CNT_MFOT_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_MFOT')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFOT')] = data['opened_last9M_CNT_MFOT'][i] / opened_closed_last9M_CNT_MFOT_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_MFOT')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFOT')] = data['opened_last1Y_CNT_MFOT'][i] / opened_closed_last1Y_CNT_MFOT_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_MFOT')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFOT')] = data['opened_last2Y_CNT_MFOT'][i] / opened_closed_last2Y_CNT_MFOT_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_MFOT')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFOT')] = data['opened_last3Y_CNT_MFOT'][i] / opened_closed_last3Y_CNT_MFOT_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_MFOT')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_PLBL')] = data['opened_last3M_CNT_PLBL'][i] / opened_closed_last3M_CNT_PLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_PLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_PLBL')] = data['opened_last6M_CNT_PLBL'][i] / opened_closed_last6M_CNT_PLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_PLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_PLBL')] = data['opened_last9M_CNT_PLBL'][i] / opened_closed_last9M_CNT_PLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_PLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_PLBL')] = data['opened_last1Y_CNT_PLBL'][i] / opened_closed_last1Y_CNT_PLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_PLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_PLBL')] = data['opened_last2Y_CNT_PLBL'][i] / opened_closed_last2Y_CNT_PLBL_val
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_PLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_PLBL')] = data['opened_last3Y_CNT_PLBL'][i] / opened_closed_last3Y_CNT_PLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_PLBL')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_PLRLBL')] = data['opened_last3M_CNT_PLRLBL'][i] / opened_closed_last3M_CNT_PLRLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_PLRLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_PLRLBL')] = data['opened_last6M_CNT_PLRLBL'][i] / opened_closed_last6M_CNT_PLRLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_PLRLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_PLRLBL')] = data['opened_last9M_CNT_PLRLBL'][i] / opened_closed_last9M_CNT_PLRLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_PLRLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_PLRLBL')] = data['opened_last1Y_CNT_PLRLBL'][i] / opened_closed_last1Y_CNT_PLRLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_PLRLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_PLRLBL')] = data['opened_last2Y_CNT_PLRLBL'][i] / opened_closed_last2Y_CNT_PLRLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_PLRLBL')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_PLRLBL')] = data['opened_last3Y_CNT_PLRLBL'][i] / opened_closed_last3Y_CNT_PLRLBL_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_PLRLBL')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_SEC')] = data['opened_last3M_CNT_SEC'][i] / opened_closed_last3M_CNT_SEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_SEC')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_SEC')] = data['opened_last6M_CNT_SEC'][i] / opened_closed_last6M_CNT_SEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_SEC')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_SEC')] = data['opened_last9M_CNT_SEC'][i] / opened_closed_last9M_CNT_SEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_SEC')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_SEC')] = data['opened_last1Y_CNT_SEC'][i] / opened_closed_last1Y_CNT_SEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_SEC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_SEC')] = data['opened_last2Y_CNT_SEC'][i] / opened_closed_last2Y_CNT_SEC_val 
    except: 
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_SEC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_SEC')] = data['opened_last3Y_CNT_SEC'][i] / opened_closed_last3Y_CNT_SEC_val 
    except: 
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_SEC')] = "NaN"
    


    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_UNSEC')] = data['opened_last3M_CNT_UNSEC'][i] / opened_closed_last3M_CNT_UNSEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_UNSEC')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_UNSEC')] = data['opened_last6M_CNT_UNSEC'][i] / opened_closed_last6M_CNT_UNSEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_UNSEC')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_UNSEC')] = data['opened_last9M_CNT_UNSEC'][i] / opened_closed_last9M_CNT_UNSEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_UNSEC')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_UNSEC')] = data['opened_last1Y_CNT_UNSEC'][i] / opened_closed_last1Y_CNT_UNSEC_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_UNSEC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_UNSEC')] = data['opened_last2Y_CNT_UNSEC'][i] / opened_closed_last2Y_CNT_UNSEC_val 
    except: 
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_UNSEC')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_UNSEC')] = data['opened_last3Y_CNT_UNSEC'][i] / opened_closed_last3Y_CNT_UNSEC_val 
    except: 
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_UNSEC')] = "NaN"
    


    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_OTH')] = data['opened_last3M_CNT_OTH'][i] / opened_closed_last3M_CNT_OTH_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last3M_CNT_OTH')] = "NaN"

    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_OTH')] = data['opened_last6M_CNT_OTH'][i] / opened_closed_last6M_CNT_OTH_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last6M_CNT_OTH')] = "NaN"
    
    try: 
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_OTH')] = data['opened_last9M_CNT_OTH'][i] / opened_closed_last9M_CNT_OTH_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last9M_CNT_OTH')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_OTH')] = data['opened_last1Y_CNT_OTH'][i] / opened_closed_last1Y_CNT_OTH_val 
    except:
        data.iat[i,data.columns.get_loc('opened_closed_last1Y_CNT_OTH')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_OTH')] = data['opened_last2Y_CNT_OTH'][i] / opened_closed_last2Y_CNT_OTH_val 
    except: 
        data.iat[i,data.columns.get_loc('opened_closed_last2Y_CNT_OTH')] = "NaN"
    
    try:
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_OTH')] = data['opened_last3Y_CNT_OTH'][i] / opened_closed_last3Y_CNT_OTH_val 
    except: 
        data.iat[i,data.columns.get_loc('opened_closed_last3Y_CNT_OTH')] = "NaN"
    




data.head()

,_ID,startTime,dateOpenedOrDisbursed,dateClosed,accountType,startTime_Date,diff_startTime_dateOpened,opened_last3M_CNT,opened_last6M_CNT,opened_last9M_CNT,...,opened_closed_last9M_CNT_SEC,opened_closed_last1Y_CNT_SEC,opened_closed_last2Y_CNT_SEC,opened_closed_last3Y_CNT_SEC,opened_closed_last3M_CNT_UNSEC,opened_closed_last6M_CNT_UNSEC,opened_closed_last9M_CNT_UNSEC,opened_closed_last1Y_CNT_UNSEC,opened_closed_last2Y_CNT_UNSEC,opened_closed_last3Y_CNT_UNSEC
0,25056002948,"[2020-07-28 06:56:21.616000, 2020-07-28 06:56:...","[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...","[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[55, 7, 22, 24, 26, 33, 33, 35, 37, 37, 40, 48...",0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25057004362,"[2020-07-28 06:39:26.277000, 2020-07-28 06:39:...","[2019-12-27, 2018-12-11]","[NaT, NaT]","[PL, AL]","[2020-07-28, 2020-07-28]","[7, 20]",0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25065002005,[2020-07-28 07:00:50.530000],[2013-11-28],[2014-04-30],[PLBL],[2020-07-28],[80],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25150006776,"[2020-07-28 06:24:14.232000, 2020-07-28 06:24:...","[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...","[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[0, 1, 1, 2, 2, 2, 3, 15, 19, 21, 25, 32, 38]",7,7,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25244001089,"[2020-07-28 06:34:27.226000, 2020-07-28 06:34:...","[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...","[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,...","[2020-07-28, 2020-07-28, 2020-07-28, 2020-07-2...","[74, 8, 12, 20, 25, 39, 42, 45, 49, 50, 73, 80...",0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
data2 = data[['_ID','dateOpenedOrDisbursed','opened_last3M_CNT_GL','opened_closed_last3M_CNT_GL','dateClosed','accountType']]
data2.head()

,_ID,dateOpenedOrDisbursed,opened_last3M_CNT_GL,opened_closed_last3M_CNT_GL,dateClosed,accountType
0,25056002948,"[2016-01-11, 2019-12-28, 2018-09-29, 2018-07-2...",0,NaN,"[NaT, NaT, 2019-12-28, 2019-08-16, 2019-01-31,...","[HL, GL, GL, GL, CD, BL, BL, GL, GL, GL, CD, O..."
1,25057004362,"[2019-12-27, 2018-12-11]",0,NaN,"[NaT, NaT]","[PL, AL]"
2,25065002005,[2013-11-28],0,NaN,[2014-04-30],[PLBL]
3,25150006776,"[2020-07-22, 2020-07-02, 2020-06-19, 2020-06-0...",6,6,"[NaT, NaT, NaT, NaT, NaT, 2020-06-19, NaT, NaT...","[GL, GL, GL, GL, GL, GL, PL, CD, CD, PLBL, PLB..."
4,25244001089,"[2014-06-07, 2019-12-02, 2019-07-24, 2018-11-1...",0,NaN,"[2016-02-29, NaT, 2019-11-13, NaT, NaT, 2018-1...","[PLBL, GL, GL, HL, GL, PLBL, GL, GL, AL, PLBL,..."

Extracting Derived time variable (Set 4)
--
For an applicant, count all the loan accounts which have been opened in last (1, 2, 3 year) and gap between the open dates <= (3, 6 months)

In [44]:
data['dateOpened_gap3M_last1Y_CNT'] = 0
data['dateOpened_gap3M_last2Y_CNT'] = 0
data['dateOpened_gap3M_last3Y_CNT'] = 0
data['dateOpened_gap6M_last1Y_CNT'] = 0
data['dateOpened_gap6M_last2Y_CNT'] = 0
data['dateOpened_gap6M_last3Y_CNT'] = 0


data['dateOpened_gap3M_last1Y_CNT'] = data['dateOpened_gap3M_last1Y_CNT'].astype(object)
data['dateOpened_gap3M_last2Y_CNT'] = data['dateOpened_gap3M_last2Y_CNT'].astype(object)
data['dateOpened_gap3M_last3Y_CNT'] = data['dateOpened_gap3M_last3Y_CNT'].astype(object)
data['dateOpened_gap6M_last1Y_CNT'] = data['dateOpened_gap6M_last1Y_CNT'].astype(object)
data['dateOpened_gap6M_last2Y_CNT'] = data['dateOpened_gap6M_last2Y_CNT'].astype(object)
data['dateOpened_gap6M_last3Y_CNT'] = data['dateOpened_gap6M_last3Y_CNT'].astype(object)

gap_three_mon_rel = relativedelta(months = 3)
gap_six_mon_rel = relativedelta(months = 6)

In [95]:
def common_elements(list1, list2):
    return len([element for element in list1 if element in list2])
    


def search_dt_gap_cnt(i, j, accountType_var, startTime_Date, date_before_period, dateOpened_dateClosed_list, accountType_list, gap_month_relative):
    opened_last_list = []
    time_range=[]
    count = 0
    
    for p in range(len(accountType_list)):
        if startTime_Date > dateOpened_dateClosed_list[p] >= date_before_period and dateOpened_dateClosed_list[p]!= "NaT":
            opened_last_list.append(dateOpened_dateClosed_list[p])
            
    opened_last_list = sorted(opened_last_list)
    opened_last_list_len = len(opened_last_list)

    gap_month_relative = relativedelta(months = 3)

    #datesx = [[] for i in range(len(opened_last_list))]
    #opened_last_list[q]=str(opened_last_list[q])
    
    #opened_last_list = [dt.datetime.strptime(date, "%Y-%m-%d").date for date in opened_last_list]

    for q in range(len(opened_last_list)):
        
        gap_month_period = opened_last_list[q] + gap_month_relative
        #gap_month_period = dt.datetime.strptime(opened_last_list[q], "%Y-%m-%d") + gap_month_relative
        
        
        for s in range(q+1, opened_last_list_len):
            if opened_last_list[s] != '1111-01-01' and gap_month_period > opened_last_list[s] >= opened_last_list[q]:
                
                opened_last_list[s] = dt.datetime(1111, 1, 1).date
                count = count+1
                
#         gap_month_period=str(gap_month_period)
#         opened_last_list[q]=str(opened_last_list[q])
#         datesx[q] = list(rrule.rrule(rrule.DAILY, dtstart=parser.parse(opened_last_list[q]), until=parser.parse(gap_month_period)))

#     opened_last_list = [dt.datetime.strptime(date, "%Y-%m-%d") for date in opened_last_list]

#     date_list = []
#     for s in range(opened_last_list_len):
#         date_list = date_list + datesx[s]

#     date_list.sort()

#     count = common_elements(opened_last_list,date_list)

    return count
    
    
    
    
    
    
#     for q in range(len(opened_last_list)):
#         gap_month_period = opened_last_list[q] + gap_month_relative
#         time_range.append(pd.date_range(opened_last_list[q], gap_month_period))
#         #time_range.append(DateTimeRange(opened_last_list[q], gap_month_period))
    
#     #time_range_set = set(time_range)
    
#     not_in_range_list = [a for a in opened_last_list if not a in time_range_set or time_range_set.remove(a)]
    
#     count = opened_last_list_len - len(not_in_range_list)
    
#     return count

In [97]:
for i in range(data.shape[0]):
    dateOpened_gap3M_last1Y_CNT_val = 0
    dateOpened_gap3M_last2Y_CNT_val = 0
    dateOpened_gap3M_last3Y_CNT_val = 0
    dateOpened_gap6M_last1Y_CNT_val = 0
    dateOpened_gap6M_last2Y_CNT_val = 0
    dateOpened_gap6M_last3Y_CNT_val = 0
    date_before_1Y = data['startTime_Date'][i][0] + one_year_rel
    #mask = (df['dateOpenedOrDisbursed'] < date_before_1Y) & (df['dateOpenedOrDisbursed']!= "NaT")
    
    
    mask = (pd.to_datetime(data['dateOpenedOrDisbursed'][i]) > pd.to_datetime(date_before_1Y)) & (pd.to_datetime(data['dateOpenedOrDisbursed'][i]) != "NaT")
    
    filtered_df = pd.DataFrame({"dateOpenedOrDisbursed":date_data['dateOpenedOrDisbursed'].loc[mask]}).sort_values('dateOpenedOrDisbursed')
    opened_last_list3Y = sorted(filtered_df['dateOpenedOrDisbursed'])
    # from itertools import combinations
    # combinatio= [",".join(map(str, comb)) for comb in combinations(opened_last_list, 2)]
    gap_month_relative = relativedelta(months=3)
    count_of_account =0
    set_visited_date = set()
    for date in opened_last_list3Y:
        sublist =[]
        if date in set_visited_date:
            continue
        date_after_3M = date + datetime.timedelta(days=90)
        mask=[]
        diiff_days =(pd.to_datetime(opened_last_list3Y)-pd.to_datetime(date_after_3M)).days
        mask = (abs(diiff_days)<=90 ) & (
                pd.to_datetime(opened_last_list3Y) != "NaT")
        if True in mask:
            sub_filtered_df = pd.DataFrame({"dateOpenedOrDisbursed":filtered_df['dateOpenedOrDisbursed'].loc[mask]})
            sublist = sorted(sub_filtered_df['dateOpenedOrDisbursed'])
            dateOpened_gap3M_last1Y_CNT_val = dateOpened_gap3M_last1Y_CNT_val+len(sublist)
            if len(opened_last_list3Y)>1:
                set_visited_date.update(sublist)
                #opened_last_list3Y = sorted(list(set(opened_last_list3Y)-set(sublist)))
            if len(opened_last_list3Y)==1:
                continue
    #print(filtered_df)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    data.iat[i,data.columns.get_loc('dateOpened_gap3M_last1Y_CNT')] =  dateOpened_gap3M_last1Y_CNT_val
    data.iat[i,data.columns.get_loc('dateOpened_gap3M_last2Y_CNT')] =  dateOpened_gap3M_last2Y_CNT_val
    data.iat[i,data.columns.get_loc('dateOpened_gap3M_last3Y_CNT')] =  dateOpened_gap3M_last3Y_CNT_val    
    data.iat[i,data.columns.get_loc('dateOpened_gap6M_last1Y_CNT')] =  dateOpened_gap6M_last1Y_CNT_val
    data.iat[i,data.columns.get_loc('dateOpened_gap6M_last2Y_CNT')] =  dateOpened_gap6M_last2Y_CNT_val
    data.iat[i,data.columns.get_loc('dateOpened_gap6M_last3Y_CNT')] =  dateOpened_gap6M_last3Y_CNT_val

NameError: name 'date_data' is not defined

In [58]:
month_day_dict= {"1":30,"2":60,"3":90,"4":120,"5":150,"6":180}

In [59]:
from itertools import combinations

def get_month_gap_cout(year_gap_list,no_of_months,gapMVariable):
    days = month_day_dict[str(no_of_months)]
    print("########",days)
    datepair = [i for i in combinations(year_gap_list, 2)]
    for pair in datepair:
        diiff_days = (pd.to_datetime(pair[0]) - pd.to_datetime(pair[1])).days
        if (diiff_days>=-90)and (diiff_days<=days):
            gapMVariable = gapMVariable +1
            
    return gapMVariable

In [60]:
def get_year_mask(datefeatureframe,datetocompaire):
    mask = (pd.to_datetime(datefeatureframe) > pd.to_datetime(datetocompaire)) & (pd.to_datetime(datefeatureframe) != "NaT")
    return mask

In [72]:
import datetime
for i in range(data.shape[0]):
    dateOpened_gap3M_last1Y_CNT_val = 0
    dateOpened_gap3M_last2Y_CNT_val = 0
    dateOpened_gap3M_last3Y_CNT_val = 0
    dateOpened_gap6M_last1Y_CNT_val = 0
    dateOpened_gap6M_last2Y_CNT_val = 0
    dateOpened_gap6M_last3Y_CNT_val = 0

    date_data = pd.DataFrame({'dateOpenedOrDisbursed':pd.to_datetime(data['dateOpenedOrDisbursed'][i])})
    date_before_1Y = data['startTime_Date'][i][0] + one_year_rel
    #mask = (date_data['dateOpenedOrDisbursed'] < date_before_1Y) & (date_data['dateOpenedOrDisbursed'] != "NaT")
    mask = (pd.to_datetime(data['dateOpenedOrDisbursed'][i]) > pd.to_datetime(date_before_1Y)) & (pd.to_datetime(data['dateOpenedOrDisbursed'][i]) != "NaT")

    filtered_df = pd.DataFrame({"dateOpenedOrDisbursed":date_data['dateOpenedOrDisbursed'].loc[mask]}).sort_values('dateOpenedOrDisbursed')
    opened_last_list3Y = sorted(filtered_df['dateOpenedOrDisbursed'])
    # from itertools import combinations
    # combinatio= [",".join(map(str, comb)) for comb in combinations(opened_last_list, 2)]
    gap_month_relative = relativedelta(months=3)
    count_of_account =0
    # from itertools import combinations
    # datepair = [i for i in combinations(opened_last_list3Y, 2)]
    # for pair in datepair:
    #     diiff_days = (pd.to_datetime(pair[0]) - pd.to_datetime(pair[1])).days
    #     if (diiff_days>=-90)and (diiff_days<=90):
    #         dateOpened_gap3M_last1Y_CNT_val = dateOpened_gap3M_last1Y_CNT_val +1
    set_visited_date = set()

    #for date in opened_last_list3Y:
    for idx, date in enumerate(opened_last_list3Y):
        sublist =[]
        if date in set_visited_date:
            if idx+1<len(opened_last_list3Y):
                if opened_last_list3Y[idx+1] in set_visited_date:
                    continue
            else:
                continue
        date_after_3M = date + datetime.timedelta(days=90)
        mask=[]
        diiff_days =(pd.to_datetime(opened_last_list3Y)-pd.to_datetime(date_after_3M)).days

        from itertools import combinations
        c2 = [i for i in combinations(opened_last_list3Y, 2)]
        mask = ((diiff_days>=-90) & (diiff_days<0)) & (
                pd.to_datetime(opened_last_list3Y) != "NaT")
        if sum(mask)>1:
            if True in mask:
                sub_filtered_df = pd.DataFrame({"dateOpenedOrDisbursed":filtered_df['dateOpenedOrDisbursed'].loc[mask]})
                sublist = sorted(sub_filtered_df['dateOpenedOrDisbursed'])
                if date in set_visited_date:
                    dateOpened_gap3M_last1Y_CNT_val = dateOpened_gap3M_last1Y_CNT_val + len(sublist)-1
                else:
                    dateOpened_gap3M_last1Y_CNT_val = dateOpened_gap3M_last1Y_CNT_val+len(sublist)
                if len(opened_last_list3Y)>1:
                    set_visited_date.update(sublist)
                    #opened_last_list3Y = sorted(list(set(opened_last_list3Y)-set(sublist)))
                if len(opened_last_list3Y)==1:
                    pass
    data.iat[i, data.columns.get_loc('dateOpened_gap3M_last1Y_CNT')] = dateOpened_gap3M_last1Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap3M_last2Y_CNT')] = dateOpened_gap3M_last2Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap3M_last3Y_CNT')] = dateOpened_gap3M_last3Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap6M_last1Y_CNT')] = dateOpened_gap6M_last1Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap6M_last2Y_CNT')] = dateOpened_gap6M_last2Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap6M_last3Y_CNT')] = dateOpened_gap6M_last3Y_CNT_val

In [69]:
import datetime
for i in range(data.shape[0]):
    dateOpened_gap3M_last1Y_CNT_val = 0
    dateOpened_gap3M_last2Y_CNT_val = 0
    dateOpened_gap3M_last3Y_CNT_val = 0
    dateOpened_gap6M_last1Y_CNT_val = 0
    dateOpened_gap6M_last2Y_CNT_val = 0
    dateOpened_gap6M_last3Y_CNT_val = 0

    date_data = pd.DataFrame({'dateOpenedOrDisbursed':pd.to_datetime(data['dateOpenedOrDisbursed'][i])})
    date_before_1Y = data['startTime_Date'][i][0] + one_year_rel
    date_before_2Y = data['startTime_Date'][i][0] + two_year_rel
    date_before_3Y = data['startTime_Date'][i][0] + three_year_rel
    #mask = (date_data['dateOpenedOrDisbursed'] < date_before_1Y) & (date_data['dateOpenedOrDisbursed'] != "NaT")
    mask1Y = get_year_mask(data['dateOpenedOrDisbursed'][i],date_before_1Y)
    mask2Y = get_year_mask(data['dateOpenedOrDisbursed'][i],date_before_2Y)
    mask3Y = get_year_mask(data['dateOpenedOrDisbursed'][i],date_before_3Y)

    filtered_df1Y = sorted(pd.DataFrame({"dateOpenedOrDisbursed":date_data['dateOpenedOrDisbursed'].loc[mask1Y]})['dateOpenedOrDisbursed'])
    filtered_df2Y = sorted(pd.DataFrame({"dateOpenedOrDisbursed":date_data['dateOpenedOrDisbursed'].loc[mask2Y]})['dateOpenedOrDisbursed'])
    filtered_df3Y = sorted(pd.DataFrame({"dateOpenedOrDisbursed":date_data['dateOpenedOrDisbursed'].loc[mask3Y]})['dateOpenedOrDisbursed'])
    dateOpened_gap3M_last1Y_CNT_val =  get_month_gap_cout(filtered_df1Y,3,dateOpened_gap3M_last1Y_CNT_val)
    dateOpened_gap3M_last2Y_CNT_val =  get_month_gap_cout(filtered_df2Y,3,dateOpened_gap3M_last2Y_CNT_val)
    dateOpened_gap3M_last3Y_CNT_val =  get_month_gap_cout(filtered_df3Y,3,dateOpened_gap3M_last3Y_CNT_val)
    print(dateOpened_gap3M_last3Y_CNT_val)
    data.iat[i, data.columns.get_loc('dateOpened_gap3M_last1Y_CNT')] = dateOpened_gap3M_last1Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap3M_last2Y_CNT')] = dateOpened_gap3M_last2Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap3M_last3Y_CNT')] = dateOpened_gap3M_last3Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap6M_last1Y_CNT')] = dateOpened_gap6M_last1Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap6M_last2Y_CNT')] = dateOpened_gap6M_last2Y_CNT_val
    data.iat[i, data.columns.get_loc('dateOpened_gap6M_last3Y_CNT')] = dateOpened_gap6M_last3Y_CNT_val
    # from itertools import combinations
    # combinatio= [",".join(map(str, comb)) for comb in combinations(opened_last_list, 2)]

5
0
0
22
1
7
0
0
2
6
2
189
2
0
0
0
0
1
17
0
0
0
6
3
0
0
21
0
24
0
1
0
2
0
0
8
1
0
0
9
0
1
6
6
0
1
15
0
4
14
10
1
1
0
3
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
3
0
0
3
3
0
0
0
0
1
0
0
0
4
0
0
0
0
0
0
0
0
1
0
13
0
85
0
0
21
0
11
29
1
4
0
2
0
0
1
0
0
6
11
7
14
33
2
0
1
11
10
0
16
3
15
4
0
0
3
0
1
9
0
0
1
1
0
0
0
30
0
0
0
0
3
1
2
0
0
0
0
0
3
0
0
13
0
1
0
0
0
0
0
1
0
4
2
1
2
20
0
55
1
1
0
0
95
28
8
0
0
0
0
1
0
1
0
1
211
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
27
2
0
1
20
0
0
0
0
0
0
0
9
0
0
0
0
0
0
0
1
0
1
0
0
0
3
0
0
2
0
0
0
0
10
5
0
1
25
0
0
0
6
33
1
0
0
0
0
0
0
1
0
0
0
0
25
1
2
0
0
0
0
0
24
0
1
1
4
0
45
3
0
6
1
69
1
0
1
0
1
0
0
9
1
3
0
1
12
1
0
0
17
117
0
0
1
0
1
0
1
153
1
11
1
4
0
0
9
0
3
8
227
0
7
14
1
0
0
0
1
0
0
0
38
5
5
10
0
0
0
77
1
0
0
1
10
0
0
2
0
0
0
1
1
0
6
0
0
2
1
7
0
6
4
0
18
30
0
3
0
0
9
2
2
0
1
0
1
1
4
0
3
27
0
0
0
5
0
2
9
0
0
23
0
0
1
0
1
15
7
0
0
0
1
1
0
0
0
0
0
2
0
0
0
0
0
0
0
9
14
0
1
4
5
1
0
0
0
23
1
1
4
5
0
0
1
1
0
0
1
2
0
0
0
12
0
0
0
3
0
0
0
0
284
5
15
1
0
1
0
0
0
6
3
0
13
0
3
6
23
9
0
0
17
3
0
0
1
7
21
0
0
0
3
0
0
4
0
0
11
0
0
1
0
0
0
88
1
0
0
0
1
0
1
44
0
0
3
19
0
0
0
5
4
0
3
0
1
28
0
0
0
18
1
0
0
0
0
0
17
28
22
0
0
0
1
0
5
7
3
1
0
0
4
58
2
1
8
0
0
1
0
0
1
1
0
2
0
0
19
0
0
4
0
1
10
0
0
0
0
6
0
0
0
1
8
0
0
0
0
5
1
0
3
53
1
201
1
89
0
0
0
0

In [347]:
# for i in range(data.shape[0]):
#     dateOpened_gap3M_last1Y_CNT_val = 0
#     dateOpened_gap3M_last2Y_CNT_val = 0
#     dateOpened_gap3M_last3Y_CNT_val = 0
#     dateOpened_gap6M_last1Y_CNT_val = 0
#     dateOpened_gap6M_last2Y_CNT_val = 0
#     dateOpened_gap6M_last3Y_CNT_val = 0
    
#     for j in range(len(data['dateOpenedOrDisbursed'][i])):            
#         date_before_1Y = data['startTime_Date'][i][j] + one_year_rel
#         date_before_2Y = data['startTime_Date'][i][j] + two_year_rel
#         date_before_3Y = data['startTime_Date'][i][j] + three_year_rel
            
#         #dateOpened_gap3M_last1Y_CNT_val = search_dt_gap_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i], gap_three_mon_rel)
#         #dateOpened_gap3M_last2Y_CNT_val = search_dt_gap_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i], gap_three_mon_rel)
#         #dateOpened_gap3M_last3Y_CNT_val = search_dt_gap_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i], gap_three_mon_rel)
#         #dateOpened_gap6M_last1Y_CNT_val = search_dt_gap_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_1Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i], gap_six_mon_rel)
#         #dateOpened_gap6M_last2Y_CNT_val = search_dt_gap_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_2Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i], gap_six_mon_rel)
#         dateOpened_gap6M_last3Y_CNT_val = search_dt_gap_cnt(i, j, data['accountType'][i][j], data['startTime_Date'][i][j], date_before_3Y, data['dateOpenedOrDisbursed'][i], data['accountType'][i], gap_six_mon_rel)

#     data.iat[i,data.columns.get_loc('dateOpened_gap3M_last1Y_CNT')] =  dateOpened_gap3M_last1Y_CNT_val
#     data.iat[i,data.columns.get_loc('dateOpened_gap3M_last2Y_CNT')] =  dateOpened_gap3M_last2Y_CNT_val
#     data.iat[i,data.columns.get_loc('dateOpened_gap3M_last3Y_CNT')] =  dateOpened_gap3M_last3Y_CNT_val    
#     data.iat[i,data.columns.get_loc('dateOpened_gap6M_last1Y_CNT')] =  dateOpened_gap6M_last1Y_CNT_val
#     data.iat[i,data.columns.get_loc('dateOpened_gap6M_last2Y_CNT')] =  dateOpened_gap6M_last2Y_CNT_val
#     data.iat[i,data.columns.get_loc('dateOpened_gap6M_last3Y_CNT')] =  dateOpened_gap6M_last3Y_CNT_val

# data.head()

TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'relativedelta'

In [74]:
data2 = data[['_ID','dateOpenedOrDisbursed','dateOpened_gap3M_last1Y_CNT','dateOpened_gap3M_last2Y_CNT','dateOpened_gap3M_last3Y_CNT']]
data2.tail()

,_ID,dateOpenedOrDisbursed,dateOpened_gap3M_last1Y_CNT,dateOpened_gap3M_last2Y_CNT,dateOpened_gap3M_last3Y_CNT
588,88966000131,"[2020-03-07, 2020-03-05, 2020-02-04, 2020-02-0...",14,0,0
589,898471420000001,"[2012-10-13, 2011-06-11, 2013-02-04, 2017-04-2...",0,0,0
590,907671420000009,[2019-03-20],0,0,0
591,910311420000011,[2020-04-30],0,0,0
592,911101420000008,"[2019-05-30, 2018-09-06, 2016-02-29, 2015-09-08]",0,0,0

In [316]:
print(data["dateOpenedOrDisbursed"][3])

[datetime.date(2020, 7, 22), datetime.date(2020, 7, 2), datetime.date(2020, 6, 19), datetime.date(2020, 6, 2), datetime.date(2020, 6, 2), datetime.date(2020, 5, 30), datetime.date(2020, 4, 30), datetime.date(2019, 5, 8), datetime.date(2019, 1, 4), datetime.date(2018, 11, 8), datetime.date(2018, 6, 27), datetime.date(2017, 12, 11), datetime.date(2017, 5, 25)]