In [12]:
import numpy as np
import pandas as pd

import datetime as dt
from datetime import date

import time

In [13]:
test_df = pd.read_csv('cibil_test.csv')
#test_df = pd.read_csv('one.csv')
#test_df.head(5)
test_df.shape

(6226, 33)

In [14]:
df = test_df[test_df['bureauName']=='CIBIL']

df.reset_index(drop=True, inplace=True)

df.to_csv('cibil.csv')
#df.head()

In [15]:
def get_unique_values(values):
    unique = []
    for piece in values:
        if piece not in unique:
            unique.append(piece)
    return unique

id_list = list(df['ID'].values)
unq_id_list = get_unique_values(id_list)

In [16]:
def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

#hasNumbers('45')

In [19]:
filename = 'b.csv'

for chunk in pd.read_csv(filename, chunksize=1000):
    #print('type: %s shape %s' % (type(chunk), chunk.shape))
    start_time = time.time()
    
    std_last1_mon = list()
    std_last3_mon_diff = list()
    std_last3_mon = list()
    std_last6_mon_diff = list()
    std_last6_mon = list()
    std_last1_yr_diff = list()
    std_last1_yr = list()
    std_last2_yr_diff = list()
    std_last2_yr = list()
    std_last3_yr_diff = list()
    std_last3_yr = list()
    matching = list()


    for x in range(0,chunk.shape[0]):
        if (chunk['mo_diff_ld_drc'][x]==-1):
            std_last1_mon.append('unknown')
        elif (chunk['mo_diff_ld_drc'][x]==1) and (chunk['payHistComp'][x][0]=='STD'):
            std_last1_mon.append(1)
        else:
            std_last1_mon.append(0)

        if (chunk['mo_diff_ld_drc'][x]==-1):
            std_last3_mon_diff.append('unknown')
        elif (chunk['mo_diff_ld_drc'][x]>1) and (chunk['mo_diff_ld_drc'][x]<4):
            std_last3_mon_diff.append(1)
        else:
            std_last3_mon_diff.append(0)

        if (chunk['mo_diff_ld_drc'][x]==-1):
            std_last6_mon_diff.append('unknown')
        elif (chunk['mo_diff_ld_drc'][x]>1) and (chunk['mo_diff_ld_drc'][x]<7):
            std_last6_mon_diff.append(1)
        else:
            std_last6_mon_diff.append(0)

        if (chunk['mo_diff_ld_drc'][x]==-1):
            std_last1_yr_diff.append('unknown')
        elif (chunk['mo_diff_ld_drc'][x]>1) and (chunk['mo_diff_ld_drc'][x]<13):
            std_last1_yr_diff.append(1)
        else:
            std_last1_yr_diff.append(0)

        if (chunk['mo_diff_ld_drc'][x]==-1):
            std_last2_yr_diff.append('unknown')
        elif (chunk['mo_diff_ld_drc'][x]>1) and (chunk['mo_diff_ld_drc'][x]<25):
            std_last2_yr_diff.append(1)
        else:
            std_last2_yr_diff.append(0)

        if (chunk['mo_diff_ld_drc'][x]==-1):
            std_last3_yr_diff.append('unknown')
        elif (chunk['mo_diff_ld_drc'][x]>1) and (chunk['mo_diff_ld_drc'][x]<37):
            std_last3_yr_diff.append(1)
        else:
            std_last3_yr_diff.append(0)

    chunk['std_last3_mon_diff'] = pd.Series(std_last3_mon_diff).values
    chunk['std_last6_mon_diff'] = pd.Series(std_last6_mon_diff).values
    chunk['std_last1_yr_diff'] = pd.Series(std_last1_yr_diff).values
    chunk['std_last2_yr_diff'] = pd.Series(std_last2_yr_diff).values
    chunk['std_last3_yr_diff'] = pd.Series(std_last3_yr_diff).values

    for x in range(0, chunk.shape[0]):
        if (chunk['std_last3_mon_diff'][x]=='unknown'):
            std_last3_mon.append('unknown')
        elif (chunk['std_last3_mon_diff'][x]==1):
            for i in range(0, 3-chunk['mo_diff_ld_drc'][x]):
                #print(i)
                matching.append(chunk['payHistComp'][x][i])
            if any('STD' in s for s in matching):
                std_last3_mon.append(1)
            else:
                std_last3_mon.append(0)
            #print(matching)    
            matching = list()
        else:
            std_last3_mon.append(0)

        if (chunk['std_last6_mon_diff'][x]=='unknown'):
            std_last6_mon.append('unknown')
        elif (chunk['std_last6_mon_diff'][x]==1):
            for i in range(0, 6-chunk['mo_diff_ld_drc'][x]):
                #print(i)
                matching.append(chunk['payHistComp'][x][i])
            if any('STD' in s for s in matching):
                std_last6_mon.append(1)
            else:
                std_last6_mon.append(0)
            #print(matching)    
            matching = list()
        else:
            std_last6_mon.append(0)

        if (chunk['std_last1_yr_diff'][x]=='unknown'):
            std_last1_yr.append('unknown')
        elif (chunk['std_last1_yr_diff'][x]==1) and (len(chunk['payHistComp'][x])>=12):
            for i in range(0, 12-chunk['mo_diff_ld_drc'][x]):
                #print(i)
                matching.append(chunk['payHistComp'][x][i])
            if any('STD' in s for s in matching):
                std_last1_yr.append(1)
            else:
                std_last1_yr.append(0)
            #print(matching)    
            matching = list()
        else:
            std_last1_yr.append(0)

        if (chunk['std_last2_yr_diff'][x]=='unknown'):
            std_last2_yr.append('unknown')
        elif (chunk['std_last2_yr_diff'][x]==1) and (len(chunk['payHistComp'][x])>=24):
            for i in range(0, 24-chunk['mo_diff_ld_drc'][x]):
                #print(i)
                matching.append(chunk['payHistComp'][x][i])
            if any('STD' in s for s in matching):
                std_last2_yr.append(1)
            else:
                std_last2_yr.append(0)
            #print(matching)    
            matching = list()
        else:
            std_last2_yr.append(0)

        if (chunk['std_last3_yr_diff'][x]=='unknown'):
            std_last3_yr.append('unknown')
        elif (chunk['std_last3_yr_diff'][x]==1) and (len(chunk['payHistComp'][x])==36):
            for i in range(0, 36-chunk['mo_diff_ld_drc'][x]):
                #print(i)
                matching.append(chunk['payHistComp'][x][i])
            if any('STD' in s for s in matching):
                std_last3_yr.append(1)
            else:
                std_last3_yr.append(0)
            #print(matching)    
            matching = list()
        else:
            std_last3_yr.append(0)

    chunk['STD1M_flag'] = pd.Series(std_last1_mon).values
    #print(chunk['STD1M_flag'].value_counts()) 

    chunk['STD3M_flag'] = pd.Series(std_last3_mon).values
    #print(chunk['STD3M_flag'].value_counts())

    chunk['STD6M_flag'] = pd.Series(std_last6_mon).values
    #print(chunk['STD6M_flag'].value_counts())

    chunk['STD1Y_flag'] = pd.Series(std_last1_yr).values
    #print(chunk['STD1Y_flag'].value_counts())

    chunk['STD2Y_flag'] = pd.Series(std_last2_yr).values
    #print(chunk['STD2Y_flag'].value_counts())

    chunk['STD3Y_flag'] = pd.Series(std_last3_yr).values
    #print(chunk['STD3Y_flag'].value_counts())

    print("%s seconds" % (time.time() - start_time))

0.20602083206176758 seconds

KeyError: 0

In [20]:
chunk['paymentHist1']

1000    9009009009009009009009009009009009009009009009...
1001                                000000000000000000000
1002                          STDSTDSTDSTDSTDSTDSTDSTDSTD
1003                             STDSTDSTDSTDSTDSTDSTDSTD
1004                       STDSTDSTDSTDSTDSTDSTDSTDSTDSTD
                              ...
1995                                              missing
1996                                               000000
1997                                               000000
1998                                   000000000000000000
1999                             000000000000000000000000
Name: paymentHist1, Length: 1000, dtype: object

In [8]:
filename = 'cibil.csv'

filtered = []

for chunk in pd.read_csv(filename, chunksize=1000):
    filtered = chunk

In [9]:
filtered

,Unnamed: 0,ID,age,gender,empType,education,addrsCategory,pinCode,addrsStateCode,phoneType,...,loanTenure,loginDate,dateReportedAndCertified,dateOpenedOrDisbursed,dateClosed,PHSD,PHED,suitFiledOrWilfulDefault,paymentHist1,paymentHist2
4000,4000,40126000261,31,Male,NaN,NaN,3.0,160002.0,4.0,1.0,...,0,2020-07-28T06:24:37.526Z,22052019.0,21102016.0,22042017.0,1052019.0,1102016.0,NaN,000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...,XXXXXXXXXXXXXXXXXXXXX000000000000000000000
4001,4001,40126000261,31,Male,NaN,NaN,3.0,160002.0,4.0,1.0,...,0,2020-07-28T06:24:37.526Z,22052019.0,16052016.0,19112016.0,1052019.0,1062016.0,NaN,000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000000000...
4002,4002,3028CD0066004,40,Male,SELF-EMPLOYED,12TH,2.0,413709.0,27.0,1.0,...,12,2020-07-28T06:24:30.618Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4003,4003,590181420000472,26,Male,Non-Government,UNDER GRADUATE,2.0,456001.0,23.0,1.0,...,0,2020-07-28T06:24:21.956Z,31122019.0,19092019.0,16122019.0,1122019.0,1092019.0,NaN,000010000000,NaN
4004,4004,590181420000472,26,Male,Non-Government,UNDER GRADUATE,2.0,456001.0,23.0,1.0,...,0,2020-07-28T06:24:21.956Z,30092019.0,20082019.0,19092019.0,1092019.0,1082019.0,NaN,000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4457,4457,84616000072,33,Male,NaN,NaN,3.0,695603.0,32.0,1.0,...,0,2020-07-28T06:20:02.796Z,31012020.0,5122019.0,NaN,1012020.0,1122019.0,NaN,000000,NaN
4458,4458,84616000072,33,Male,NaN,NaN,3.0,695603.0,32.0,1.0,...,0,2020-07-28T06:20:02.796Z,30062020.0,22112019.0,NaN,1062020.0,1112019.0,NaN,000000000000000000000000,NaN
4459,4459,84616000072,33,Male,NaN,NaN,3.0,695603.0,32.0,1.0,...,0,2020-07-28T06:20:02.796Z,31102019.0,10062019.0,NaN,1102019.0,1062019.0,NaN,000000000000000,NaN
4460,4460,84616000072,33,Male,NaN,NaN,3.0,695603.0,32.0,1.0,...,0,2020-07-28T06:20:02.796Z,31052020.0,12102016.0,NaN,1052020.0,1062017.0,NaN,000XXX0000000000000000260250000000000000000000...,0000000000000000000000000000000000000000000000...
4461,4461,44697001451,44,Male,NaN,NaN,2.0,573128.0,29.0,1.0,...,0,2020-07-28T06:19:45.640Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN